// Copyright (c) ScanDrix Authors. All rights reserved.
// Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).

package operations

import (
	"strings"
	"testing"
)

func TestDetectLanguageAndGenerated(t *testing.T) {
	if DetectLanguage("main.go") != "Go" {
		t.Fatalf("expected Go, got %s", DetectLanguage("main.go"))
	}
	if DetectLanguage("app.tsx") != "TypeScript" {
		t.Fatalf("expected TypeScript, got %s", DetectLanguage("app.tsx"))
	}
	if DetectLanguage("script.py") != "Python" {
		t.Fatalf("expected Python, got %s", DetectLanguage("script.py"))
	}

	if !IsGeneratedFile("api.pb.go") {
		t.Fatalf("expected api.pb.go to be generated")
	}
	if !IsGeneratedFile("package-lock.json") {
		t.Fatalf("expected package-lock.json to be generated")
	}
	if IsGeneratedFile("handler.go") {
		t.Fatalf("did not expect handler.go to be generated")
	}
}

func TestParseDiffStream_MultiFile(t *testing.T) {
	rawDiff := `diff --git a/main.go b/main.go
index 1111111..2222222 100644
--- a/main.go
+++ b/main.go
@@ -1,5 +1,6 @@
 package main
 
-func oldMain() {}
+func newMain() {
+	// new logic
+}
 
diff --git a/logo.png b/logo.png
Binary files a/logo.png and b/logo.png differ
diff --git a/api.pb.go b/api.pb.go
new file mode 100644
--- /dev/null
+++ b/api.pb.go
@@ -0,0 +1,2 @@
+// Code generated by protoc-gen-go. DO NOT EDIT.
+package api
`

	summary, err := ParseDiffStream(strings.NewReader(rawDiff))
	if err != nil {
		t.Fatalf("ParseDiffStream failed: %v", err)
	}

	if summary.TotalFiles != 3 {
		t.Fatalf("expected 3 files, got %d", summary.TotalFiles)
	}

	if summary.TotalAdditions != 5 { // 3 in main.go, 2 in api.pb.go
		t.Fatalf("expected 5 additions, got %d", summary.TotalAdditions)
	}

	if summary.TotalDeletions != 1 { // 1 in main.go
		t.Fatalf("expected 1 deletion, got %d", summary.TotalDeletions)
	}

	if !summary.HasBinaryFiles {
		t.Fatalf("expected HasBinaryFiles to be true")
	}

	if summary.GeneratedFiles != 1 {
		t.Fatalf("expected 1 generated file, got %d", summary.GeneratedFiles)
	}

	// Verify main.go hunk lines
	mainFile := summary.Files[0]
	if len(mainFile.Hunks) != 1 {
		t.Fatalf("expected 1 hunk in main.go, got %d", len(mainFile.Hunks))
	}
	hunk := mainFile.Hunks[0]
	if hunk.OldStart != 1 || hunk.NewStart != 1 {
		t.Fatalf("unexpected hunk starts: old=%d, new=%d", hunk.OldStart, hunk.NewStart)
	}
}
