package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"
)

//go:generate env SCANDRIX_UPDATE_ENV_CONTRACT=1 go test -run TestGenerateEnvContract -count=1 .

// updateEnv regenerates the contract when set. A plain env var, because
// `go generate` cannot forward test-only flags to a test binary.
const updateEnv = "SCANDRIX_UPDATE_ENV_CONTRACT"

// TestGenerateEnvContract regenerates the contract from the source. Go's AST
// scan, not a regex, is the source of truth: a naive grep also matches
// string literals and comments and produces names the program never reads.
func TestGenerateEnvContract(t *testing.T) {
	if os.Getenv(updateEnv) == "" {
		t.Skip("set " + updateEnv + "=1 to regenerate (go generate ./cmd/envcheck)")
	}

	found := scanEnvNames(t)

	// A variable is boot-required only if the process cannot start without it.
	// Almost everything else in .env.example is an optional integration, and
	// treating those as mandatory would block a minimal local environment on
	// things like XAI_API_KEY. The authoritative boot-critical set lives in
	// main.go next to the check that enforces it.
	declared := map[string]bool{}
	for name := range bootCriticalEnv {
		declared[name] = true
	}

	names := make([]string, 0, len(found))
	for n := range found {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Code generated by: go generate ./cmd/envcheck. DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("// envContract is every environment variable the application reads via\n")
	b.WriteString("// os.Getenv / os.LookupEnv, classified as boot-required or optional.\n")
	b.WriteString("//\n")
	b.WriteString("// AUDIT_REMEDIATION.md F-76: envcheck previously validated 13 hand-written\n")
	b.WriteString("// names while the code read several hundred, so a missing or renamed variable\n")
	b.WriteString("// surfaced as a runtime failure instead of a startup failure. This list is\n")
	b.WriteString("// generated from the source and drift-checked by the tests in this package,\n")
	b.WriteString("// so it cannot silently fall behind again.\n")
	b.WriteString("type envContract struct {\n\tName     string\n\tRequired bool\n}\n\n")
	b.WriteString("var envContractNames = []envContract{\n")
	for _, n := range names {
		b.WriteString(fmt.Sprintf("\t{Name: %q, Required: %v},\n", n, declared[n]))
	}
	b.WriteString("}\n")

	out := filepath.Join("env_contract_gen.go")
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		t.Fatalf("write %s: %v", out, err)
	}
	t.Logf("regenerated %s with %d names (%d required)", out, len(names), countRequired(names, declared))
}

func countRequired(names []string, declared map[string]bool) int {
	n := 0
	for _, name := range names {
		if declared[name] {
			n++
		}
	}
	return n
}

func moduleRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatalf("resolve module root: %v", err)
	}
	return root
}

// scanEnvNames walks the module and collects every environment variable name
// read through os.Getenv / os.LookupEnv.
func scanEnvNames(t *testing.T) map[string]bool {
	t.Helper()

	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatalf("resolve module root: %v", err)
	}

	found := map[string]bool{}
	fset := token.NewFileSet()

	err = filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			switch info.Name() {
			case ".git", "node_modules", "vendor", "dist", "build", ".agents", ".claude":
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}

		f, perr := parser.ParseFile(fset, path, nil, 0)
		if perr != nil {
			return nil // a file we cannot parse cannot contribute names
		}
		ast.Inspect(f, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			pkg, ok := sel.X.(*ast.Ident)
			if !ok || pkg.Name != "os" {
				return true
			}
			if sel.Sel.Name != "Getenv" && sel.Sel.Name != "LookupEnv" {
				return true
			}
			if len(call.Args) == 0 {
				return true
			}
			lit, ok := call.Args[0].(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				return true
			}
			name, uerr := strconv.Unquote(lit.Value)
			if uerr != nil {
				return true
			}
			if name != "" && name == strings.ToUpper(name) && strings.Contains(name, "_") {
				found[name] = true
			}
			return true
		})
		return nil
	})
	if err != nil {
		t.Fatalf("walk module: %v", err)
	}
	return found
}

// The generated contract must cover every variable the code reads. Without
// this, envcheck would quietly shrink back to a partial list - the exact
// problem F-76 recorded.
func TestEnvContractCoversEveryVariableReadByCode(t *testing.T) {
	found := scanEnvNames(t)

	contract := map[string]bool{}
	for _, c := range envContractNames {
		if contract[c.Name] {
			t.Errorf("duplicate entry in generated env contract: %s", c.Name)
		}
		contract[c.Name] = true
	}

	var missing []string
	for name := range found {
		if !contract[name] {
			missing = append(missing, name)
		}
	}
	sort.Strings(missing)

	if len(missing) > 0 {
		t.Errorf("env contract is missing %d variable(s) read by application code: %v\n"+
			"Regenerate with: go generate ./cmd/envcheck", len(missing), missing)
	}
	t.Logf("contract covers %d variables; %d are read by code", len(contract), len(found))
}

// Contract entries must not name variables the code never reads; that would
// make envcheck demand configuration for something that does not exist.
func TestEnvContractHasNoStaleEntries(t *testing.T) {
	found := scanEnvNames(t)

	var stale []string
	for _, c := range envContractNames {
		if !found[c.Name] {
			stale = append(stale, c.Name)
		}
	}
	sort.Strings(stale)

	if len(stale) > 0 {
		t.Errorf("env contract has %d stale entr(ies) no longer read by code: %v\n"+
			"Regenerate with: go generate ./cmd/envcheck", len(stale), stale)
	}
}
