package catalog

import "github.com/scandrix/backend/pkg/models"

// GetCloudRules returns 15 Cloud and Infrastructure-as-Code security rules.
func GetCloudRules() []RuleDefinition {
	return []RuleDefinition{
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-AWS-ACCESS-KEY"),
			Code:        "SEC-CLOUD-AWS-ACCESS-KEY",
			Name:        "Hardcoded AWS Access Key",
			Category:    "SECURITY_SECRET",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-798",
			RegexRule:   `(?i)(AKIA|A3T|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}`,
			Description: "Detected potential hardcoded AWS Access Key ID in source code.",
			Remediation: "Remove the key immediately, rotate it in AWS IAM, and load from environment variables.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-GITHUB-PAT"),
			Code:        "SEC-CLOUD-GITHUB-PAT",
			Name:        "Hardcoded GitHub Personal Access Token",
			Category:    "SECURITY_SECRET",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-798",
			RegexRule:   `ghp_[0-9a-zA-Z]{36}`,
			Description: "Detected cleartext GitHub Personal Access Token.",
			Remediation: "Revoke the token on GitHub immediately and inject via Doppler or environment secrets.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-PRIVATE-KEY-BLOCK"),
			Code:        "SEC-CLOUD-PRIVATE-KEY-BLOCK",
			Name:        "Hardcoded Private Key Block",
			Category:    "SECURITY_SECRET",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-798",
			RegexRule:   `-----BEGIN (RSA|EC|OPENSSH|PGP|ENCRYPTED)? ?PRIVATE KEY-----`,
			Description: "Asymmetric private cryptographic key committed to repository.",
			Remediation: "Delete the key, revoke certificates associated with it, and store in a KMS/Vault.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-AWS-IAM-WILDCARD"),
			Code:        "SEC-CLOUD-AWS-IAM-WILDCARD",
			Name:        "AWS IAM Policy with Administrator Wildcard (*)",
			Category:    "CLOUD_IAM",
			Language:    "CLOUD",
			PathPattern: "*.{tf,json,yaml,yml}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-250",
			RegexRule:   `(?i)"Action"\s*:\s*["']\*["']|"Resource"\s*:\s*["']\*["']|"Effect"\s*:\s*"Allow"`,
			Description: "Allowing full wildcard action or resource access (*:*) in IAM policies grants unbounded administrative privileges.",
			Remediation: "Enforce least-privilege IAM policies specifying explicit API actions (e.g. s3:GetObject) and scoped ARN resource paths.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-S3-PUBLIC-READ"),
			Code:        "SEC-CLOUD-S3-PUBLIC-READ",
			Name:        "S3 Bucket Configured with Public Read Access",
			Category:    "CLOUD_STORAGE",
			Language:    "CLOUD",
			PathPattern: "*.{tf,json,yaml,yml}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-284",
			RegexRule:   `(?i)(acl\s*=\s*["']public-read(?:-write)?["']|block_public_acls\s*=\s*false|ignore_public_acls\s*=\s*false)`,
			Description: "Configuring S3 buckets with public read or disabled public access blocks exposes corporate data to the public internet.",
			Remediation: "Enable all S3 Public Access Block settings: block_public_acls = true, block_public_policy = true.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-EBS-UNENCRYPTED"),
			Code:        "SEC-CLOUD-EBS-UNENCRYPTED",
			Name:        "Unencrypted EBS Volume or Database Instance",
			Category:    "CLOUD_STORAGE",
			Language:    "CLOUD",
			PathPattern: "*.{tf,json,yaml,yml}",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-311",
			RegexRule:   `(?i)encrypted\s*=\s*false|storage_encrypted\s*=\s*false`,
			Description: "Storing data on unencrypted EBS volumes or RDS instances fails compliance standards and leaves data at rest unprotected.",
			Remediation: "Enable KMS-managed encryption: encrypted = true and specify a customer-managed KMS key.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-SECURITY-GROUP-0000"),
			Code:        "SEC-CLOUD-SECURITY-GROUP-0000",
			Name:        "Security Group Ingress Open to 0.0.0.0/0 on Sensitive Ports",
			Category:    "CLOUD_NETWORK",
			Language:    "CLOUD",
			PathPattern: "*.{tf,json,yaml,yml}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-284",
			RegexRule:   `(?i)(?:cidr_blocks|cidr_ip)\s*=\s*\[?["']0\.0\.0\.0/0["']\]?.*(?:from_port\s*=\s*(?:22|3389|5432|3306|27017|6379)|to_port\s*=\s*(?:22|3389|5432|3306|27017|6379))`,
			Description: "Allowing inbound ingress from 0.0.0.0/0 on management or database ports (SSH 22, RDP 3389, PostgreSQL 5432) exposes services to brute-force attacks.",
			Remediation: "Restrict ingress to trusted internal corporate CIDR ranges, bastion hosts, or VPN gateways.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-K8S-HOSTPID"),
			Code:        "SEC-CLOUD-K8S-HOSTPID",
			Name:        "Kubernetes Pod Sharing Host PID Namespace",
			Category:    "KUBERNETES_SECURITY",
			Language:    "CLOUD",
			PathPattern: "*.{yaml,yml,json}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-250",
			RegexRule:   `(?i)hostPID\s*:\s*true|hostIPC\s*:\s*true`,
			Description: "Sharing the host PID/IPC namespace allows a container to inspect, trace, and signal processes running on the host node.",
			Remediation: "Disable hostPID and hostIPC (set to false or omit) in Kubernetes PodSpec definitions.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-K8S-PRIVILEGED-CONTAINER"),
			Code:        "SEC-CLOUD-K8S-PRIVILEGED-CONTAINER",
			Name:        "Kubernetes Container with Privileged SecurityContext",
			Category:    "KUBERNETES_SECURITY",
			Language:    "CLOUD",
			PathPattern: "*.{yaml,yml,json}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-250",
			RegexRule:   `(?i)securityContext:\s*\n(?:\s+.*\n)*\s+privileged:\s*true`,
			Description: "Privileged containers have full root access to all host devices and can easily escape container confinement.",
			Remediation: "Set securityContext.privileged: false and use PodSecurityStandards (Restricted profile).",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-K8S-RUN-AS-NON-ROOT"),
			Code:        "SEC-CLOUD-K8S-RUN-AS-NON-ROOT",
			Name:        "Kubernetes Container Missing runAsNonRoot Enforcement",
			Category:    "KUBERNETES_SECURITY",
			Language:    "CLOUD",
			PathPattern: "*.{yaml,yml,json}",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-250",
			RegexRule:   `(?i)runAsNonRoot\s*:\s*false|runAsUser\s*:\s*0`,
			Description: "Failing to enforce non-root execution in Kubernetes PodSecurityContext allows workloads to run as root UID 0.",
			Remediation: "Configure securityContext: { runAsNonRoot: true, runAsUser: 10001 }.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-TERRAFORM-CLEARTEXT-PASSWORD"),
			Code:        "SEC-CLOUD-TERRAFORM-CLEARTEXT-PASSWORD",
			Name:        "Cleartext Database Password in Terraform Resource",
			Category:    "CLOUD_SECRET",
			Language:    "CLOUD",
			PathPattern: "*.tf",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-798",
			RegexRule:   `(?i)(password|admin_password|master_password)\s*=\s*["'][^"'\$]{8,}["']`,
			Description: "Hardcoding administrative database passwords in Terraform manifests commits secrets to source control.",
			Remediation: "Reference secrets from AWS Secrets Manager data sources or Terraform variable definitions marked sensitive = true.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-CLOUDFRONT-HTTP-ALLOWED"),
			Code:        "SEC-CLOUD-CLOUDFRONT-HTTP-ALLOWED",
			Name:        "CloudFront Distribution Allowing Unencrypted HTTP Traffic",
			Category:    "CLOUD_NETWORK",
			Language:    "CLOUD",
			PathPattern: "*.{tf,json,yaml,yml}",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-319",
			RegexRule:   `(?i)viewer_protocol_policy\s*=\s*["']allow-all["']`,
			Description: "Allowing plain HTTP connections without redirection exposes user traffic to eavesdropping and manipulation.",
			Remediation: "Set viewer_protocol_policy = 'redirect-to-https' or 'https-only'.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-GCP-SERVICE-ACCOUNT-KEY"),
			Code:        "SEC-CLOUD-GCP-SERVICE-ACCOUNT-KEY",
			Name:        "Hardcoded Google Cloud Service Account Private Key",
			Category:    "CLOUD_SECRET",
			Language:    "CLOUD",
			PathPattern: "*",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-798",
			RegexRule:   `(?i)"type"\s*:\s*"service_account".*"private_key"\s*:\s*"-----BEGIN PRIVATE KEY-----`,
			Description: "Committing GCP service account JSON key credentials allows attackers to impersonate cloud service accounts.",
			Remediation: "Revoke the service account key immediately in Google Cloud Console and switch to Workload Identity Federation.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-AZURE-STORAGE-HTTP"),
			Code:        "SEC-CLOUD-AZURE-STORAGE-HTTP",
			Name:        "Azure Storage Account Enabling Insecure HTTP",
			Category:    "CLOUD_STORAGE",
			Language:    "CLOUD",
			PathPattern: "*.{tf,json,yaml,yml}",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-319",
			RegexRule:   `(?i)enable_https_traffic_only\s*=\s*false`,
			Description: "Disabling HTTPS-only traffic for Azure Storage Accounts permits plaintext REST API calls over HTTP.",
			Remediation: "Set enable_https_traffic_only = true in Azure Storage Account configurations.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-RDS-PUBLICLY-ACCESSIBLE"),
			Code:        "SEC-CLOUD-RDS-PUBLICLY-ACCESSIBLE",
			Name:        "RDS Instance Configured with Public IP Address",
			Category:    "CLOUD_DATABASE",
			Language:    "CLOUD",
			PathPattern: "*.{tf,json,yaml,yml}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-284",
			RegexRule:   `(?i)publicly_accessible\s*=\s*true`,
			Description: "Provisioning relational databases with public IP addresses exposes internal database instances to internet scans.",
			Remediation: "Set publicly_accessible = false and deploy databases into private VPC subnets.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-ALB-DROP-HTTP-HEADERS"),
			Code:        "SEC-CLOUD-ALB-DROP-HTTP-HEADERS",
			Name:        "Load Balancer Allowing Invalid HTTP Header Characters",
			Category:    "CLOUD_NETWORK",
			Language:    "CLOUD",
			PathPattern: "*.{tf,json,yaml,yml}",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-444",
			RegexRule:   `(?i)drop_invalid_header_fields\s*=\s*false`,
			Description: "Failing to drop invalid HTTP header fields exposes backend reverse proxies to HTTP request smuggling attacks.",
			Remediation: "Set drop_invalid_header_fields = true on Application Load Balancers.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-K8S-READONLY-ROOTFS"),
			Code:        "SEC-CLOUD-K8S-READONLY-ROOTFS",
			Name:        "Kubernetes Container with Writable Root Filesystem",
			Category:    "KUBERNETES_SECURITY",
			Language:    "CLOUD",
			PathPattern: "*.{yaml,yml,json}",
			Severity:    models.SeverityLow,
			CWE:         "CWE-732",
			RegexRule:   `(?i)readOnlyRootFilesystem\s*:\s*false`,
			Description: "Allowing write access to the container root filesystem facilitates malware persistence if compromised.",
			Remediation: "Configure securityContext: { readOnlyRootFilesystem: true } and use emptyDir volumes for temporary writes.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-CLOUD-CLOUDTRAIL-LOG-VALIDATION"),
			Code:        "SEC-CLOUD-CLOUDTRAIL-LOG-VALIDATION",
			Name:        "AWS CloudTrail Log File Validation Disabled",
			Category:    "CLOUD_AUDIT",
			Language:    "CLOUD",
			PathPattern: "*.{tf,json,yaml,yml}",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-354",
			RegexRule:   `(?i)enable_log_file_validation\s*=\s*false`,
			Description: "Disabling CloudTrail log file validation prevents cryptographic detection of log tampering or deletion.",
			Remediation: "Set enable_log_file_validation = true on all AWS CloudTrail trails.",
		},
	}
}
