package catalog

import "github.com/scandrix/backend/pkg/models"

// GetCPPRules returns 12 C and C++ memory safety and secure coding rules.
func GetCPPRules() []RuleDefinition {
	return []RuleDefinition{
		{
			ID:          GenerateDeterministicUUID("CPP-BUFFER-OVERFLOW-STRCPY"),
			Code:        "CPP-BUFFER-OVERFLOW-STRCPY",
			Name:        "Unbounded String Copy (strcpy / strcat / sprintf)",
			Category:    "CPP_MEMORY_SAFETY",
			Language:    "CPP",
			PathPattern: "*.{c,cpp,cc,h,hpp}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-120",
			RegexRule:   `\b(?:strcpy|strcat|sprintf|vsprintf|gets)\s*\(`,
			Description: "Functions like strcpy, strcat, and gets do not perform destination buffer bounds checking, leading to stack buffer overflows.",
			Remediation: "Use bounded functions: strncpy, snprintf, or std::string.",
		},
		{
			ID:          GenerateDeterministicUUID("CPP-FORMAT-STRING-VULNERABILITY"),
			Code:        "CPP-FORMAT-STRING-VULNERABILITY",
			Name:        "Format String Vulnerability in printf / syslog",
			Category:    "CPP_SECURITY",
			Language:    "CPP",
			PathPattern: "*.{c,cpp,cc,h,hpp}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-134",
			RegexRule:   `\b(?:printf|syslog|fprintf)\s*\(\s*(?:buf|str|user_input|input)\s*\)`,
			Description: "Passing user input directly as the format string allows attackers to read and write arbitrary memory using %x and %n specifiers.",
			Remediation: "Always specify a literal format string: printf(\"%s\", buf).",
		},
		{
			ID:          GenerateDeterministicUUID("CPP-USE-AFTER-FREE"),
			Code:        "CPP-USE-AFTER-FREE",
			Name:        "Potential Use-After-Free of Deallocated Pointer",
			Category:    "CPP_MEMORY_SAFETY",
			Language:    "CPP",
			PathPattern: "*.{c,cpp,cc,h,hpp}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-416",
			RegexRule:   `free\s*\(\s*[a-zA-Z0-9_]+\s*\);`,
			Description: "Accessing memory after calling free() or delete results in undefined behavior, heap corruption, and arbitrary code execution.",
			Remediation: "Set pointer to NULL after freeing (ptr = NULL) or use C++ smart pointers (std::unique_ptr, std::shared_ptr).",
		},
		{
			ID:          GenerateDeterministicUUID("CPP-DOUBLE-FREE"),
			Code:        "CPP-DOUBLE-FREE",
			Name:        "Double Free of Memory Buffer",
			Category:    "CPP_MEMORY_SAFETY",
			Language:    "CPP",
			PathPattern: "*.{c,cpp,cc,h,hpp}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-415",
			RegexRule:   `delete\s+[a-zA-Z0-9_]+;\s*delete\s+[a-zA-Z0-9_]+;`,
			Description: "Freeing the same heap memory address twice corrupts internal memory management structures in glibc/ptmalloc.",
			Remediation: "Set pointers to NULL immediately after freeing or adopt RAII and smart pointers.",
		},
		{
			ID:          GenerateDeterministicUUID("CPP-MALLOC-WITHOUT-NULL-CHECK"),
			Code:        "CPP-MALLOC-WITHOUT-NULL-CHECK",
			Name:        "malloc / calloc Return Value Used Without NULL Verification",
			Category:    "CPP_RELIABILITY",
			Language:    "CPP",
			PathPattern: "*.{c,cpp,cc,h,hpp}",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-476",
			RegexRule:   `\b(?:malloc|calloc)\s*\(`,
			Description: "Failing to verify malloc return value causes immediate NULL pointer dereference crashes when memory is exhausted.",
			Remediation: "Always check if pointer == NULL before dereferencing allocated memory.",
		},
		{
			ID:          GenerateDeterministicUUID("CPP-INTEGER-OVERFLOW-ALLOCATION"),
			Code:        "CPP-INTEGER-OVERFLOW-ALLOCATION",
			Name:        "Integer Overflow in Memory Allocation Size Calculation",
			Category:    "CPP_MEMORY_SAFETY",
			Language:    "CPP",
			PathPattern: "*.{c,cpp,cc,h,hpp}",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-190",
			RegexRule:   `malloc\s*\(\s*(?:\w+\s*\*\s*sizeof|\w+\s*\*\s*\w+)\s*\)`,
			Description: "Multiplying user-controlled counts by sizeof() can overflow integer bounds, allocating a smaller buffer than required and leading to heap overflow.",
			Remediation: "Check for multiplication overflow before allocating or use calloc(count, size).",
		},
		{
			ID:          GenerateDeterministicUUID("CPP-INSECURE-RANDOM-RAND"),
			Code:        "CPP-INSECURE-RANDOM-RAND",
			Name:        "Use of Insecure rand() / srand() for Cryptographic Context",
			Category:    "CPP_CRYPTO",
			Language:    "CPP",
			PathPattern: "*.{c,cpp,cc,h,hpp}",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-338",
			RegexRule:   `\b(?:rand|srand)\s*\(`,
			Description: "Standard C rand() has short periods and is completely predictable.",
			Remediation: "Use OpenSSL RAND_bytes(), arc4random(), or /dev/urandom for security tokens.",
		},
		{
			ID:          GenerateDeterministicUUID("CPP-RAW-MEMCPY-OVERLAP"),
			Code:        "CPP-RAW-MEMCPY-OVERLAP",
			Name:        "memcpy with Potentially Overlapping Memory Regions",
			Category:    "CPP_MEMORY_SAFETY",
			Language:    "CPP",
			PathPattern: "*.{c,cpp,cc,h,hpp}",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-119",
			RegexRule:   `memcpy\s*\(\s*\w+\s*,\s*\w+\s*\+`,
			Description: "memcpy() has undefined behavior if source and destination memory buffers overlap.",
			Remediation: "Use memmove() for overlapping memory buffers.",
		},
		{
			ID:          GenerateDeterministicUUID("CPP-ARRAY-BOUNDS-FIXED-INDEX"),
			Code:        "CPP-ARRAY-BOUNDS-FIXED-INDEX",
			Name:        "Negative or Unchecked Array Index Subscript",
			Category:    "CPP_MEMORY_SAFETY",
			Language:    "CPP",
			PathPattern: "*.{c,cpp,cc,h,hpp}",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-125",
			RegexRule:   `\w+\[\s*-\d+\s*\]`,
			Description: "Subscripting an array with negative indexes reads unmapped memory preceding the buffer.",
			Remediation: "Ensure array indices are unsigned and bounded by container size.",
		},
		{
			ID:          GenerateDeterministicUUID("CPP-SYSTEM-COMMAND-EXEC"),
			Code:        "CPP-SYSTEM-COMMAND-EXEC",
			Name:        "system() Call with Variable Command String",
			Category:    "CPP_SECURITY",
			Language:    "CPP",
			PathPattern: "*.{c,cpp,cc,h,hpp}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-78",
			RegexRule:   `system\s*\(\s*(?:cmd|buf|str|user_input)\s*\)`,
			Description: "Executing commands via system() passes arguments to /bin/sh, exposing the application to command injection.",
			Remediation: "Use execve() or posix_spawn() with explicit argument vectors without invoking a shell.",
		},
		{
			ID:          GenerateDeterministicUUID("CPP-UNINITIALIZED-VARIABLE"),
			Code:        "CPP-UNINITIALIZED-VARIABLE",
			Name:        "Pointer Declaration Without Initialization",
			Category:    "CPP_CODE_QUALITY",
			Language:    "CPP",
			PathPattern: "*.{c,cpp,cc,h,hpp}",
			Severity:    models.SeverityLow,
			CWE:         "CWE-457",
			RegexRule:   `(?m)^\s*(?:char|int|void|\w+)\s*\*\s*\w+\s*;`,
			Description: "Declaring pointers without initializing them to NULL or a valid address creates wild pointers containing garbage memory.",
			Remediation: "Always initialize pointers at declaration time: char* ptr = nullptr; or char* ptr = NULL;.",
		},
		{
			ID:          GenerateDeterministicUUID("CPP-HARDCODED-CRYPTO-KEY"),
			Code:        "CPP-HARDCODED-CRYPTO-KEY",
			Name:        "Hardcoded AES or RSA Key Array in C/C++ Source",
			Category:    "CPP_SECRET",
			Language:    "CPP",
			PathPattern: "*.{c,cpp,cc,h,hpp}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-798",
			RegexRule:   `const\s+(?:unsigned\s+char|char|uint8_t)\s+\w+(?:_key|_secret|Key)\s*\[\s*\d*\s*\]\s*=\s*\{`,
			Description: "Embedding cryptographic key byte arrays directly in compiled source code allows trivial extraction via strings or decompilation.",
			Remediation: "Load cryptographic keys at runtime from an external KMS or secure hardware module (TPM/HSM).",
		},
	}
}
