package catalog

import "github.com/scandrix/backend/pkg/models"

// GetDockerRules returns 12 Dockerfile and container security rules.
func GetDockerRules() []RuleDefinition {
	return []RuleDefinition{
		{
			ID:          GenerateDeterministicUUID("SEC-DOCKER-ROOT-USER"),
			Code:        "SEC-DOCKER-ROOT-USER",
			Name:        "Container Running as Root User",
			Category:    "CONTAINER_SECURITY",
			Language:    "DOCKER",
			PathPattern: "*Dockerfile*",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-250",
			RegexRule:   `(?m)^USER\s+(?:root|0)\s*$`,
			Description: "Running container workloads as root grants excessive kernel privileges in case of container breakout.",
			Remediation: "Create a dedicated non-root user (e.g. USER 10001:10001) in the Dockerfile.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-DOCKER-LATEST-TAG"),
			Code:        "SEC-DOCKER-LATEST-TAG",
			Name:        "Unpinned Base Image with 'latest' Tag",
			Category:    "CONTAINER_REPRODUCIBILITY",
			Language:    "DOCKER",
			PathPattern: "*Dockerfile*",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-1188",
			RegexRule:   `(?m)^FROM\s+[\w\./\-]+:(?:latest)\b|^FROM\s+[\w\./\-]+(?:\s+AS|\s*$)`,
			Description: "Using mutable image tags like 'latest' or unversioned base images causes non-reproducible builds and unexpected breaking changes.",
			Remediation: "Pin base images to explicit version tags or immutable SHA256 digests (e.g. alpine:3.21 or node:22-alpine@sha256:...).",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-DOCKER-SECRET-ENV"),
			Code:        "SEC-DOCKER-SECRET-ENV",
			Name:        "Cleartext Secret in Dockerfile ENV Instruction",
			Category:    "CONTAINER_SECURITY",
			Language:    "DOCKER",
			PathPattern: "*Dockerfile*",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-798",
			RegexRule:   `(?mi)^ENV\s+.*(?:API_KEY|SECRET|PASSWORD|TOKEN|AUTH|PRIVATE_KEY)\s*[:=]\s*["']?[^\s"']+["']?`,
			Description: "Baking secrets into ENV instructions persists them forever in the container image metadata layers.",
			Remediation: "Use Docker BuildKit secrets mount (--mount=type=secret) or inject secrets at runtime.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-DOCKER-CURL-BASH"),
			Code:        "SEC-DOCKER-CURL-BASH",
			Name:        "Piping Remote Web Script Directly to Shell",
			Category:    "CONTAINER_SUPPLY_CHAIN",
			Language:    "DOCKER",
			PathPattern: "*Dockerfile*",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-494",
			RegexRule:   `(?i)curl\s+[^\|]+\|\s*(?:bash|sh|zsh)`,
			Description: "Piping curl directly to bash executes unverified remote code without checksum or integrity verification.",
			Remediation: "Download the script to a file, verify its cryptographic SHA256 hash, and execute it separately.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-DOCKER-SUDO-INSTALLED"),
			Code:        "SEC-DOCKER-SUDO-INSTALLED",
			Name:        "Sudo Utility Installed in Production Image",
			Category:    "CONTAINER_SECURITY",
			Language:    "DOCKER",
			PathPattern: "*Dockerfile*",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-250",
			RegexRule:   `(?i)apt-get\s+install.*sudo|apk\s+add.*sudo|yum\s+install.*sudo`,
			Description: "Installing sudo in production containers increases the attack surface for local privilege escalation.",
			Remediation: "Remove sudo from production container images and configure least-privilege non-root users directly.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-DOCKER-EXPOSED-SSH"),
			Code:        "SEC-DOCKER-EXPOSED-SSH",
			Name:        "Exposing SSH Port 22 in Container",
			Category:    "CONTAINER_NETWORK",
			Language:    "DOCKER",
			PathPattern: "*Dockerfile*",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-284",
			RegexRule:   `(?m)^EXPOSE\s+.*(?:22)\b`,
			Description: "Exposing SSH daemon inside application containers violates single-concern container best practices.",
			Remediation: "Use container orchestration exec capabilities (docker exec / kubectl exec) instead of running an SSH daemon.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-DOCKER-ADD-TARBALL"),
			Code:        "SEC-DOCKER-ADD-TARBALL",
			Name:        "Use of ADD instead of COPY for Local Files",
			Category:    "CONTAINER_BEST_PRACTICE",
			Language:    "DOCKER",
			PathPattern: "*Dockerfile*",
			Severity:    models.SeverityLow,
			CWE:         "CWE-1188",
			RegexRule:   `(?m)^ADD\s+[^\s]+\s+[^\s]+`,
			Description: "ADD automatically extracts archive files and has unpredictable tar extraction behaviors.",
			Remediation: "Use COPY instead of ADD when copying local files into the container.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-DOCKER-MISSING-HEALTHCHECK"),
			Code:        "SEC-DOCKER-MISSING-HEALTHCHECK",
			Name:        "Disabled Healthcheck in Container Image",
			Category:    "CONTAINER_RELIABILITY",
			Language:    "DOCKER",
			PathPattern: "*Dockerfile*",
			Severity:    models.SeverityLow,
			CWE:         "CWE-754",
			RegexRule:   `(?m)^HEALTHCHECK\s+NONE\s*$`,
			Description: "Explicitly disabling container healthchecks prevents orchestrators from detecting deadlocks and zombie processes.",
			Remediation: "Implement an active HEALTHCHECK instruction using curl, wget, or a lightweight binary probe.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-DOCKER-ROOT-CHMOD-777"),
			Code:        "SEC-DOCKER-ROOT-CHMOD-777",
			Name:        "Overly Permissive File Permissions (chmod 777)",
			Category:    "CONTAINER_SECURITY",
			Language:    "DOCKER",
			PathPattern: "*Dockerfile*",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-732",
			RegexRule:   `(?i)chmod\s+(?:-R\s+)?(?:777|a\+rwx)`,
			Description: "Setting world-writable and executable permissions (777) allows any low-privileged user to modify executable binaries or configurations.",
			Remediation: "Use restrictive permissions such as 755 for executables or 644 for configuration files.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-DOCKER-APT-CACHE-LEAK"),
			Code:        "SEC-DOCKER-APT-CACHE-LEAK",
			Name:        "Uncleaned Package Manager Cache in Image Layer",
			Category:    "CONTAINER_OPTIMIZATION",
			Language:    "DOCKER",
			PathPattern: "*Dockerfile*",
			Severity:    models.SeverityLow,
			CWE:         "CWE-1188",
			RegexRule:   `apt-get\s+install\s+-[a-zA-Z]*y`,
			Description: "Leaving package manager caches (/var/lib/apt/lists) inflates container image size and slows pull times.",
			Remediation: "Combine package installation with cache cleanup: apt-get update && apt-get install -y --no-install-recommends pkg && rm -rf /var/lib/apt/lists/*",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-DOCKER-PRIVILEGED-COMPOSE"),
			Code:        "SEC-DOCKER-PRIVILEGED-COMPOSE",
			Name:        "Privileged Mode Enabled in Docker Compose",
			Category:    "CONTAINER_SECURITY",
			Language:    "DOCKER",
			PathPattern: "*docker-compose*.y*ml",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-250",
			RegexRule:   `(?i)privileged\s*:\s*true`,
			Description: "Running containers in privileged mode grants full host device access and eliminates container isolation boundaries.",
			Remediation: "Drop privileged mode and add only specific required Linux capabilities via cap_add (e.g. NET_ADMIN).",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-DOCKER-HOST-NETWORK-COMPOSE"),
			Code:        "SEC-DOCKER-HOST-NETWORK-COMPOSE",
			Name:        "Host Network Namespace Sharing",
			Category:    "CONTAINER_NETWORK",
			Language:    "DOCKER",
			PathPattern: "*docker-compose*.y*ml",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-284",
			RegexRule:   `(?i)network_mode\s*:\s*["']?host["']?`,
			Description: "Sharing the host network namespace disables container network isolation and exposes localhost ports to the entire host.",
			Remediation: "Use custom bridge networks and expose only specific required container ports.",
		},
	}
}
