package catalog

import "github.com/scandrix/backend/pkg/models"

// GetGolangRules returns 15 idiomatic Go code quality, concurrency, and security rules.
func GetGolangRules() []RuleDefinition {
	return []RuleDefinition{
		{
			ID:          GenerateDeterministicUUID("GOLANG-SQL-FORMAT-INJECTION"),
			Code:        "GOLANG-SQL-FORMAT-INJECTION",
			Name:        "SQL Injection via String Formatting",
			Category:    "SECURITY_INJECTION",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-89",
			RegexRule:   `fmt\.Sprintf\(["'].*(SELECT|INSERT|UPDATE|DELETE).*FROM`,
			Description: "Concatenating or formatting untrusted user input directly into SQL statements causes SQL injection.",
			Remediation: "Use parameterized queries or prepared statements ($1, $2) via pgx or database/sql.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-SHELL-COMMAND-INJECTION"),
			Code:        "GOLANG-SHELL-COMMAND-INJECTION",
			Name:        "Shell Command Injection Vulnerability",
			Category:    "SECURITY_INJECTION",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-78",
			RegexRule:   `exec\.Command\(["'](sh|bash|zsh)["'],\s*["']-c["']`,
			Description: "Spawning a subshell with -c and concatenated arguments exposes the host to arbitrary command injection.",
			Remediation: "Pass individual argument slices to exec.Command without invoking an intermediary shell.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-UNHANDLED-ERROR"),
			Code:        "GOLANG-UNHANDLED-ERROR",
			Name:        "Unhandled Function Error Return Value (_ = err)",
			Category:    "GO_ERROR_HANDLING",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-391",
			RegexRule:   `(?m)^\s*_\s*,\s*_\s*=\s*[\w\.]+\(`,
			Description: "Ignoring error return values with blank identifier '_' suppresses silent failures and corrupts application state.",
			Remediation: "Explicitly handle errors: if err != nil { return fmt.Errorf(...) }.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-MUTEX-COPY"),
			Code:        "GOLANG-MUTEX-COPY",
			Name:        "Pass by Value of Struct Containing sync.Mutex",
			Category:    "GO_CONCURRENCY",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-662",
			RegexRule:   `func\s*\([^)]*\w+\s+(?:[A-Z]\w*)\)\s+\w+.*(?:sync\.(?:RW)?Mutex)`,
			Description: "Passing a struct containing a sync.Mutex by value copies the mutex lock state, causing deadlocks or unsynchronized memory access.",
			Remediation: "Use pointer receivers (*MyStruct) for all methods on structs containing mutexes.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-DEFER-IN-LOOP"),
			Code:        "GOLANG-DEFER-IN-LOOP",
			Name:        "Defer Statement Inside Loop Scope (Resource Leak)",
			Category:    "GO_RESOURCE_MANAGEMENT",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-772",
			RegexRule:   `(?s)for\s+.*\{[^}]*defer\s+[\w\.]+\(`,
			Description: "Using defer inside a for loop delays resource release until the enclosing function exits, causing file descriptor or memory exhaustion.",
			Remediation: "Extract the loop body into a helper function or close resources explicitly inside the loop using a direct close call.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-GOROUTINE-LEAK-CHANNEL"),
			Code:        "GOLANG-GOROUTINE-LEAK-CHANNEL",
			Name:        "Unbuffered Channel Send Without Receiver (Goroutine Leak)",
			Category:    "GO_CONCURRENCY",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-400",
			RegexRule:   `go\s+func\s*\(\)\s*\{[^}]*\w+\s*<-\s*\w+[^}]*\}\(\)`,
			Description: "Launching a goroutine that sends to an unbuffered channel without guaranteed receiver causes permanent goroutine leaks.",
			Remediation: "Use buffered channels with sufficient capacity or pass context.Context to allow goroutines to exit when cancelled.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-HTTP-MISSING-BODY-CLOSE"),
			Code:        "GOLANG-HTTP-MISSING-BODY-CLOSE",
			Name:        "HTTP Response Body Not Closed",
			Category:    "GO_RESOURCE_MANAGEMENT",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-772",
			RegexRule:   `resp,\s*err\s*:=\s*http\.(?:Get|Post|Do)\(`,
			Description: "Failing to defer resp.Body.Close() prevents TCP connection reuse and causes connection pool socket starvation.",
			Remediation: "Always close HTTP response bodies: if err == nil { defer resp.Body.Close() }.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-TIME-AFTER-IN-SELECT-LOOP"),
			Code:        "GOLANG-TIME-AFTER-IN-SELECT-LOOP",
			Name:        "time.After Inside Loop Leading to High Memory Allocation",
			Category:    "GO_PERFORMANCE",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-400",
			RegexRule:   `(?s)for\s*\{[^}]*select\s*\{[^}]*case\s*<-\s*time\.After\(`,
			Description: "Calling time.After inside a select loop creates a new timer on every iteration that is not garbage collected until it expires.",
			Remediation: "Use time.NewTimer and reset it explicitly, or use time.NewTicker.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-NIL-CONTEXT-PASSED"),
			Code:        "GOLANG-NIL-CONTEXT-PASSED",
			Name:        "Passing nil Context to Function",
			Category:    "GO_BEST_PRACTICE",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-476",
			RegexRule:   `(?i)[\w\.]+\(\s*nil\s*,\s*.*\)`,
			Description: "Passing nil instead of context.Context causes panic when downstream libraries attempt to read trace spans or deadlines.",
			Remediation: "Use context.Background() or context.TODO() instead of nil.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-UNSAFE-POINTER-CONVERSION"),
			Code:        "GOLANG-UNSAFE-POINTER-CONVERSION",
			Name:        "Use of unsafe.Pointer for Arbitrary Memory Casting",
			Category:    "GO_MEMORY_SAFETY",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-119",
			RegexRule:   `unsafe\.Pointer\(`,
			Description: "Bypassing Go type safety via unsafe.Pointer risks memory corruption and breaks garbage collector invariants.",
			Remediation: "Use standard type conversions or encoding/binary instead of unsafe memory manipulation.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-MATH-RAND-FOR-CRYPTO"),
			Code:        "GOLANG-MATH-RAND-FOR-CRYPTO",
			Name:        "Insecure Random Number Generator for Security Keys",
			Category:    "GO_CRYPTO",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-338",
			RegexRule:   `(?i)(math\/rand|rand\.(?:Int|Intn|Read)).*(?:token|secret|password|nonce|salt|key|session)`,
			Description: "Using math/rand generates pseudo-random sequences predictable by attackers for security tokens.",
			Remediation: "Use crypto/rand (rand.Read(buf)) for cryptographic keys, tokens, and nonces.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-EMPTY-ERROR-CHECK"),
			Code:        "GOLANG-EMPTY-ERROR-CHECK",
			Name:        "Empty Error Handling Block (Silent Swallowing)",
			Category:    "GO_ERROR_HANDLING",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-390",
			RegexRule:   `if\s*err\s*!=\s*nil\s*\{\s*\}`,
			Description: "Checking if err != nil with an empty block silently swallows exceptions, masking failures from monitoring.",
			Remediation: "Log the error, increment failure metrics, or return the error to the caller.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-JSON-TAG-UNEXPORTED-FIELD"),
			Code:        "GOLANG-JSON-TAG-UNEXPORTED-FIELD",
			Name:        "JSON Tag on Unexported Lowercase Struct Field",
			Category:    "GO_CODE_QUALITY",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityLow,
			CWE:         "CWE-1188",
			RegexRule:   `(?m)^\s*[a-z]\w*\s+\w+\s+\x60json:`,
			Description: "Go json.Marshal ignores unexported (lowercase) struct fields, causing silent serialization data loss.",
			Remediation: "Export the struct field by capitalizing its first letter.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-CONTEXT-CANCEL-OMITTED"),
			Code:        "GOLANG-CONTEXT-CANCEL-OMITTED",
			Name:        "context.WithTimeout/WithCancel Missing defer cancel()",
			Category:    "GO_RESOURCE_MANAGEMENT",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-772",
			RegexRule:   `ctx,\s*cancel\s*:=\s*context\.With(?:Timeout|Cancel|Deadline)\(`,
			Description: "Failing to invoke cancel() keeps timer goroutines and context associations active until their deadline passes.",
			Remediation: "Immediately add defer cancel() after creating cancellable contexts.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-RACE-MAP-CONCURRENT-ACCESS"),
			Code:        "GOLANG-RACE-MAP-CONCURRENT-ACCESS",
			Name:        "Concurrent Read/Write to Standard Go Map",
			Category:    "GO_CONCURRENCY",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-362",
			RegexRule:   `go\s+func.*\{.*\w+\[.*\]\s*=.*\}`,
			Description: "Concurrent map read and write operations trigger fatal runtime panics in Go.",
			Remediation: "Protect map access with sync.RWMutex or use sync.Map.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-PANIC-IN-LIBRARY-CODE"),
			Code:        "GOLANG-PANIC-IN-LIBRARY-CODE",
			Name:        "Direct panic() Call in Production Service Code",
			Category:    "GO_RELIABILITY",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-248",
			RegexRule:   `(?m)^\s*panic\(`,
			Description: "Calling panic() terminates the entire process if not caught by a recover middleware.",
			Remediation: "Return explicit errors instead of panicking.",
		},
		{
			ID:          GenerateDeterministicUUID("GOLANG-SUBPROCESS-VARIABLE-COMMAND"),
			Code:        "GOLANG-SUBPROCESS-VARIABLE-COMMAND",
			Name:        "Unvalidated Command Name in exec.Command",
			Category:    "GO_SECURITY",
			Language:    "GO",
			PathPattern: "*.go",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-78",
			RegexRule:   `exec\.Command\(\s*(?:req\.|params|input|cmdName)`,
			Description: "Using variable user input as the executable binary name allows executing arbitrary binaries from PATH.",
			Remediation: "Hardcode the binary name as a string literal and validate all parameter slices.",
		},
	}
}
