package catalog

import "github.com/scandrix/backend/pkg/models"

// GetJavaRules returns 12 Java and Spring enterprise security and quality rules.
func GetJavaRules() []RuleDefinition {
	return []RuleDefinition{
		{
			ID:          GenerateDeterministicUUID("JAVA-LOG4SHELL-JNDI"),
			Code:        "JAVA-LOG4SHELL-JNDI",
			Name:        "Log4Shell JNDI Lookup Pattern (CVE-2021-44228)",
			Category:    "JAVA_SECURITY",
			Language:    "JAVA",
			PathPattern: "*.java",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-502",
			RegexRule:   `\$\{(?:jndi|lower|upper|sys|env):(?:ldap|rmi|dns|nis|iiop):`,
			Description: "JNDI lookup strings evaluated by vulnerable Log4j libraries trigger remote class loading and RCE.",
			Remediation: "Upgrade Log4j to >= 2.17.1 and set log4j2.formatMsgNoLookups=true.",
		},
		{
			ID:          GenerateDeterministicUUID("JAVA-INSECURE-DESERIALIZATION"),
			Code:        "JAVA-INSECURE-DESERIALIZATION",
			Name:        "Java Native ObjectInputStream Deserialization",
			Category:    "JAVA_SECURITY",
			Language:    "JAVA",
			PathPattern: "*.java",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-502",
			RegexRule:   `new\s+ObjectInputStream\([^)]+\)\.readObject\(`,
			Description: "Deserializing untrusted byte streams with ObjectInputStream executes arbitrary gadget chains (Apache Commons, Spring).",
			Remediation: "Use Jackson or Gson with polymorphic typing disabled, or use ValidatingObjectInputStream.",
		},
		{
			ID:          GenerateDeterministicUUID("JAVA-SPRING-SPEL-INJECTION"),
			Code:        "JAVA-SPRING-SPEL-INJECTION",
			Name:        "Spring Expression Language (SpEL) Injection",
			Category:    "JAVA_SECURITY",
			Language:    "JAVA",
			PathPattern: "*.java",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-94",
			RegexRule:   `SpelExpressionParser.*parseExpression\s*\(\s*(?:req|input|param|userInput)`,
			Description: "Evaluating user-controlled expressions in Spring Expression Language allows arbitrary Java code execution via T(...) syntax.",
			Remediation: "Use SimpleEvaluationContext instead of StandardEvaluationContext or avoid parsing dynamic SpEL expressions.",
		},
		{
			ID:          GenerateDeterministicUUID("JAVA-ECB-CIPHER-MODE"),
			Code:        "JAVA-ECB-CIPHER-MODE",
			Name:        "Insecure Electronic Codebook (ECB) Cipher Mode",
			Category:    "JAVA_CRYPTO",
			Language:    "JAVA",
			PathPattern: "*.java",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-327",
			RegexRule:   `Cipher\.getInstance\s*\(\s*["']AES/ECB/`,
			Description: "ECB cipher mode does not use an initialization vector (IV) and leaks plaintext structural patterns.",
			Remediation: "Use authenticated encryption: Cipher.getInstance('AES/GCM/NoPadding').",
		},
		{
			ID:          GenerateDeterministicUUID("JAVA-TRUST-ALL-CERTIFICATES"),
			Code:        "JAVA-TRUST-ALL-CERTIFICATES",
			Name:        "TrustManager Accepting All Certificates (X509TrustManager)",
			Category:    "JAVA_SECURITY",
			Language:    "JAVA",
			PathPattern: "*.java",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-295",
			RegexRule:   `class\s+\w+\s+implements\s+X509TrustManager\s*\{[^}]*checkServerTrusted\s*\([^)]*\)\s*\{\s*\}`,
			Description: "Implementing an empty checkServerTrusted() method disables SSL/TLS validation completely.",
			Remediation: "Use standard Java KeyStore validation and do not bypass checkServerTrusted.",
		},
		{
			ID:          GenerateDeterministicUUID("JAVA-XXE-DOCUMENT-BUILDER"),
			Code:        "JAVA-XXE-DOCUMENT-BUILDER",
			Name:        "XML DocumentBuilderFactory Without Disallow Doctype",
			Category:    "JAVA_SECURITY",
			Language:    "JAVA",
			PathPattern: "*.java",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-611",
			RegexRule:   `DocumentBuilderFactory\.newInstance\(\)`,
			Description: "Parsing untrusted XML without disallowing DTDs exposes applications to XXE entity expansion attacks.",
			Remediation: "Call dbf.setFeature('http://apache.org/xml/features/disallow-doctype-decl', true).",
		},
		{
			ID:          GenerateDeterministicUUID("JAVA-HARDCODED-KEYSTORE-PASSWORD"),
			Code:        "JAVA-HARDCODED-KEYSTORE-PASSWORD",
			Name:        "Hardcoded Keystore or Truststore Password",
			Category:    "JAVA_SECRET",
			Language:    "JAVA",
			PathPattern: "*.java",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-798",
			RegexRule:   `KeyStore\.load\([^,]+,\s*["'][^"']{4,32}["']\.toCharArray\(\)\)`,
			Description: "Hardcoding JKS / PKCS12 keystore passwords in source code compromises certificate private keys.",
			Remediation: "Inject keystore passwords at runtime using environment variables or a vault.",
		},
		{
			ID:          GenerateDeterministicUUID("JAVA-SPRING-CORS-ALL"),
			Code:        "JAVA-SPRING-CORS-ALL",
			Name:        "Spring @CrossOrigin with Wildcard Origin (*)",
			Category:    "JAVA_SECURITY",
			Language:    "JAVA",
			PathPattern: "*.java",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-942",
			RegexRule:   `@CrossOrigin\s*\(\s*(?:origins\s*=\s*)?["']\*["']\s*,\s*allowCredentials\s*=\s*["']true["']`,
			Description: "Allowing all origins with allowCredentials=true exposes authenticated Spring REST endpoints.",
			Remediation: "Set explicit domain origins in the @CrossOrigin annotation.",
		},
		{
			ID:          GenerateDeterministicUUID("JAVA-SYSTEM-EXIT-IN-SERVLET"),
			Code:        "JAVA-SYSTEM-EXIT-IN-SERVLET",
			Name:        "System.exit() Called in Web Application",
			Category:    "JAVA_RELIABILITY",
			Language:    "JAVA",
			PathPattern: "*.java",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-382",
			RegexRule:   `System\.exit\s*\(\s*\d+\s*\)`,
			Description: "Calling System.exit() halts the entire JVM and crashes the Tomcat / Spring Boot container for all users.",
			Remediation: "Throw an exception or return an error response instead of shutting down the JVM.",
		},
		{
			ID:          GenerateDeterministicUUID("JAVA-WEAK-PRNG-RANDOM"),
			Code:        "JAVA-WEAK-PRNG-RANDOM",
			Name:        "Use of java.util.Random for Cryptographic Nonce",
			Category:    "JAVA_CRYPTO",
			Language:    "JAVA",
			PathPattern: "*.java",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-338",
			RegexRule:   `new\s+java\.util\.Random\(\)`,
			Description: "java.util.Random produces predictable values and should not be used for security-critical tokens.",
			Remediation: "Use java.security.SecureRandom.",
		},
		{
			ID:          GenerateDeterministicUUID("JAVA-HIBERNATE-SQL-INJECTION"),
			Code:        "JAVA-HIBERNATE-SQL-INJECTION",
			Name:        "HQL / JPQL Injection via String Concatenation",
			Category:    "JAVA_SECURITY",
			Language:    "JAVA",
			PathPattern: "*.java",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-89",
			RegexRule:   `entityManager\.createQuery\s*\(\s*["'].*["']\s*\+`,
			Description: "Concatenating user input into Hibernate createQuery strings allows HQL / JPQL injection.",
			Remediation: "Use named parameters: createQuery('FROM User u WHERE u.id = :id').setParameter('id', input).",
		},
		{
			ID:          GenerateDeterministicUUID("JAVA-UNVALIDATED-REDIRECT"),
			Code:        "JAVA-UNVALIDATED-REDIRECT",
			Name:        "HttpServletResponse.sendRedirect() with Unvalidated URL",
			Category:    "JAVA_SECURITY",
			Language:    "JAVA",
			PathPattern: "*.java",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-601",
			RegexRule:   `response\.sendRedirect\s*\(\s*(?:request\.getParameter|userInput)\s*\)`,
			Description: "Redirecting users directly to URLs from request parameters facilitates open redirection attacks.",
			Remediation: "Validate target URLs against an internal allowlist.",
		},
	}
}
