package catalog

import "github.com/scandrix/backend/pkg/models"

// GetOWASPRules returns 15 comprehensive rules covering the OWASP Top 10 vulnerability categories.
func GetOWASPRules() []RuleDefinition {
	return []RuleDefinition{
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-SQLI"),
			Code:        "SEC-OWASP-SQLI",
			Name:        "SQL Injection via Unsanitized Input Formatting",
			Category:    "SECURITY_INJECTION",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-89",
			OWASP:       "A03:2021-Injection",
			RegexRule:   `(?i)(SELECT|INSERT|UPDATE|DELETE|DROP|ALTER).*(?:%s|\+.*(?:req|param|query|input|body)|concat\()`,
			Description: "Direct string formatting or raw concatenation into SQL query execution creates critical SQL injection vulnerabilities.",
			Remediation: "Use parameterized queries or prepared statements ($1, ? placeholder) provided by the database driver.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-NOSQLI"),
			Code:        "SEC-OWASP-NOSQLI",
			Name:        "NoSQL Injection via Unsanitized Query Object",
			Category:    "SECURITY_INJECTION",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-943",
			OWASP:       "A03:2021-Injection",
			RegexRule:   `(?i)(find|findOne|update|delete)\s*\(\s*(?:req\.body|req\.query|params)\s*\)`,
			Description: "Passing raw user request payloads directly to MongoDB/Mongoose or DynamoDB enables query operator injection ($gt, $ne, $where).",
			Remediation: "Explicitly sanitize and validate query parameters using a schema validator like Zod, Joi, or Pydantic.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-CMDI"),
			Code:        "SEC-OWASP-CMDI",
			Name:        "OS Command Injection via Shell Invocation",
			Category:    "SECURITY_INJECTION",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-78",
			OWASP:       "A03:2021-Injection",
			RegexRule:   `(?i)(system|exec|popen|subprocess\.call|child_process\.exec)\s*\(\s*(?:.*(?:req|input|param|\+)|f["'].*\{.*\}.*["'])`,
			Description: "Passing untrusted input directly into a shell execution function allows remote arbitrary command execution.",
			Remediation: "Avoid shell invocation. Pass arguments as an explicit array to execFile / subprocess.run(shell=False).",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-SSRF"),
			Code:        "SEC-OWASP-SSRF",
			Name:        "Server-Side Request Forgery (SSRF)",
			Category:    "SECURITY_SSRF",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-918",
			OWASP:       "A10:2021-Server-Side Request Forgery",
			RegexRule:   `(?i)(http\.Get|fetch|requests\.get|axios\.get|curl_exec)\s*\(\s*(?:req\.query|req\.body|params\[|url_from_user)`,
			Description: "Fetching remote URLs directly from user input without IP/hostname allowlisting allows attackers to access internal cloud metadata and VPC resources.",
			Remediation: "Validate target URLs against an explicit allowlist and block private IP ranges (169.254.169.254, 10.0.0.0/8, 127.0.0.1).",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-XSS-REFLECTED"),
			Code:        "SEC-OWASP-XSS-REFLECTED",
			Name:        "Cross-Site Scripting (XSS) via Unescaped Output",
			Category:    "SECURITY_XSS",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-79",
			OWASP:       "A03:2021-Injection",
			RegexRule:   `(?i)(innerHTML|outerHTML|document\.write|res\.send|render_template_string)\s*(?:=|:|\()\s*.*(?:req\.query|req\.body|req\.params)`,
			Description: "Rendering untrusted user input directly into HTML without context-aware sanitization leads to DOM-based or reflected XSS.",
			Remediation: "Use DOMPurify, standard templating auto-escaping (React JSX, Jinja2 autoescape), or textContent.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-AUTH-WEAK-HASH"),
			Code:        "SEC-OWASP-AUTH-WEAK-HASH",
			Name:        "Weak Password Hashing Algorithm",
			Category:    "SECURITY_CRYPTO",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-328",
			OWASP:       "A02:2021-Cryptographic Failures",
			RegexRule:   `(?i)(md5|sha1|sha256)\s*\(\s*(?:password|passwd|pwd)`,
			Description: "Hashing user passwords with fast unsalted or unkeyed digests (MD5, SHA-1, plain SHA-256) is vulnerable to rainbow table attacks.",
			Remediation: "Use Argon2id or bcrypt with an adaptive cost factor for password hashing.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-JWT-NONE-ALG"),
			Code:        "SEC-OWASP-JWT-NONE-ALG",
			Name:        "JWT Algorithm 'none' Bypass Vulnerability",
			Category:    "SECURITY_AUTH",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-347",
			OWASP:       "A07:2021-Identification and Authentication Failures",
			RegexRule:   `(?i)(algorithms\s*:\s*\[.*["']none["']|algorithms\s*=\s*\[.*["']none["'])`,
			Description: "Allowing 'none' algorithm in JWT signature verification allows attackers to forge administrative authentication tokens.",
			Remediation: "Enforce explicit asymmetric (RS256, ES256) or symmetric (HS256) algorithms and explicitly reject 'none'.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-INSECURE-DESERIALIZATION"),
			Code:        "SEC-OWASP-INSECURE-DESERIALIZATION",
			Name:        "Insecure Deserialization of Untrusted Data",
			Category:    "SECURITY_DESERIALIZATION",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-502",
			OWASP:       "A08:2021-Software and Data Integrity Failures",
			RegexRule:   `(?i)(pickle\.loads|yaml\.load\s*\([^,]+(?:\)|,\s*Loader\s*=\s*(?:yaml\.)?Loader)|unserialize\s*\(|readObject\s*\(\))`,
			Description: "Deserializing untrusted byte streams enables arbitrary object instantiation and Remote Code Execution (RCE).",
			Remediation: "Use safe JSON serialization or yaml.safe_load(). Avoid Python pickle or native Java serialization on untrusted input.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-XXE"),
			Code:        "SEC-OWASP-XXE",
			Name:        "XML External Entity (XXE) Processing",
			Category:    "SECURITY_XXE",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-611",
			OWASP:       "A05:2021-Security Misconfiguration",
			RegexRule:   `(?i)(XMLReaderFactory|DocumentBuilderFactory|SAXParserFactory|lxml\.etree|xml\.etree)\.newInstance.*setFeature.*false`,
			Description: "Parsing XML without disabling external entity resolution enables file disclosure, SSRF, and Denial of Service.",
			Remediation: "Disable DTD processing: setFeature('http://apache.org/xml/features/disallow-doctype-decl', true).",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-OPEN-REDIRECT"),
			Code:        "SEC-OWASP-OPEN-REDIRECT",
			Name:        "Unvalidated Open Redirect",
			Category:    "SECURITY_REDIRECT",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-601",
			OWASP:       "A01:2021-Broken Access Control",
			RegexRule:   `(?i)(res\.redirect|http\.Redirect|response\.sendRedirect|redirect_to)\s*\(\s*(?:req\.query|params\[|url_param)`,
			Description: "Redirecting users to unvalidated target URLs from query parameters facilitates credential phishing campaigns.",
			Remediation: "Validate redirect target against an internal route allowlist or relative path regex (e.g. ^/[^/\\\\]).",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-CORS-WILDCARD"),
			Code:        "SEC-OWASP-CORS-WILDCARD",
			Name:        "CORS Wildcard with Credential Sharing",
			Category:    "SECURITY_CORS",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-942",
			OWASP:       "A05:2021-Security Misconfiguration",
			RegexRule:   `(?i)(Access-Control-Allow-Origin.*["']\*["'].*Access-Control-Allow-Credentials.*true|origin\s*:\s*["']\*["'],\s*credentials\s*:\s*true)`,
			Description: "Configuring CORS Access-Control-Allow-Origin to '*' while enabling credentials allows malicious websites to steal authenticated sessions.",
			Remediation: "Specify exact allowed origin domains and avoid reflecting the Origin header with credentials enabled.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-HARDCODED-SECRET"),
			Code:        "SEC-OWASP-HARDCODED-SECRET",
			Name:        "Hardcoded High-Entropy API Secret",
			Category:    "SECURITY_SECRET",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-798",
			OWASP:       "A07:2021-Identification and Authentication Failures",
			RegexRule:   `(?i)(api_key|secret_key|private_key|auth_token|client_secret)\s*[:=]\s*["'][a-zA-Z0-9_\-]{24,}["']`,
			Description: "Storing cleartext secrets or API keys in source code leads to repository credential leakage.",
			Remediation: "Inject secrets dynamically at runtime from environment variables or a secrets manager (Doppler, AWS Secrets Manager).",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-PATH-TRAVERSAL"),
			Code:        "SEC-OWASP-PATH-TRAVERSAL",
			Name:        "Directory and Path Traversal Vulnerability",
			Category:    "SECURITY_TRAVERSAL",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-22",
			OWASP:       "A01:2021-Broken Access Control",
			RegexRule:   `(?i)(fs\.readFile|open|os\.Open|ioutil\.ReadFile|file_get_contents)\s*\(\s*(?:.*(?:req\.query|params|filename)|\.\./)`,
			Description: "Accessing filesystem paths using unvalidated user input containing '../' sequences allows reading arbitrary sensitive files.",
			Remediation: "Resolve absolute paths with filepath.Clean / path.resolve and verify the path remains within the intended root directory.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-INSECURE-TLS"),
			Code:        "SEC-OWASP-INSECURE-TLS",
			Name:        "Disabled TLS Certificate Validation",
			Category:    "SECURITY_NETWORK",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-295",
			OWASP:       "A07:2021-Identification and Authentication Failures",
			RegexRule:   `(?i)(InsecureSkipVerify\s*:\s*true|verify\s*=\s*False|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"]0['"]|rejectUnauthorized\s*:\s*false)`,
			Description: "Disabling TLS certificate verification allows Man-in-the-Middle (MitM) attackers to intercept and tamper with encrypted traffic.",
			Remediation: "Always enable TLS certificate verification and provide proper root CA certificates.",
		},
		{
			ID:          GenerateDeterministicUUID("SEC-OWASP-LOG-INJECTION"),
			Code:        "SEC-OWASP-LOG-INJECTION",
			Name:        "Log Injection and CRLF Forgery",
			Category:    "SECURITY_LOGGING",
			Language:    "ALL",
			PathPattern: "*",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-117",
			OWASP:       "A09:2021-Security Logging and Monitoring Failures",
			RegexRule:   `(?i)(logger\.(?:info|warn|error|debug)|log\.Printf|console\.log)\s*\(\s*.*(?:req\.body|req\.query|user_input).*(?:\r|\n|%0d|%0a)`,
			Description: "Logging unsanitized user input containing newline characters (CRLF) enables log injection and tampering with security audit trails.",
			Remediation: "Sanitize user inputs by stripping carriage returns and newlines before passing them to loggers.",
		},
	}
}
