package catalog

import "github.com/scandrix/backend/pkg/models"

// GetPythonRules returns 15 Python code security, performance, and reliability rules.
func GetPythonRules() []RuleDefinition {
	return []RuleDefinition{
		{
			ID:          GenerateDeterministicUUID("PY-INSECURE-EVAL-EXEC"),
			Code:        "PY-INSECURE-EVAL-EXEC",
			Name:        "Use of Dynamic Code Execution (eval/exec)",
			Category:    "PYTHON_SECURITY",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-95",
			RegexRule:   `(?i)\b(?:eval|exec)\s*\(\s*(?:request|params|user_input|input|\w+)`,
			Description: "Calling eval() or exec() on user-influenced input grants arbitrary Python code execution.",
			Remediation: "Use ast.literal_eval() for safe literal parsing or avoid dynamic code evaluation.",
		},
		{
			ID:          GenerateDeterministicUUID("PY-INSECURE-PICKLE-LOADS"),
			Code:        "PY-INSECURE-PICKLE-LOADS",
			Name:        "Insecure Deserialization via pickle or cPickle",
			Category:    "PYTHON_SECURITY",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-502",
			RegexRule:   `(?i)\b(?:pickle|cPickle|_pickle)\.(?:loads|load)\s*\(`,
			Description: "Unpickling data from untrusted sources executes arbitrary Python bytecode via __reduce__ hooks.",
			Remediation: "Use JSON, Protocol Buffers, or MessagePack for untrusted serialization.",
		},
		{
			ID:          GenerateDeterministicUUID("PY-YAML-UNSAFE-LOAD"),
			Code:        "PY-YAML-UNSAFE-LOAD",
			Name:        "PyYAML yaml.load without SafeLoader",
			Category:    "PYTHON_SECURITY",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-502",
			RegexRule:   `yaml\.load\s*\([^,)]+(?:\)|,\s*Loader\s*=\s*(?:yaml\.)?Loader)`,
			Description: "yaml.load() without SafeLoader can construct arbitrary Python objects leading to remote code execution.",
			Remediation: "Use yaml.safe_load() or specify Loader=yaml.SafeLoader.",
		},
		{
			ID:          GenerateDeterministicUUID("PY-SUBPROCESS-SHELL-TRUE"),
			Code:        "PY-SUBPROCESS-SHELL-TRUE",
			Name:        "Subprocess Invoked with shell=True",
			Category:    "PYTHON_SECURITY",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-78",
			RegexRule:   `subprocess\.(?:Popen|call|run|check_output)\s*\([^)]*shell\s*=\s*True`,
			Description: "Executing subprocesses with shell=True exposes the execution to command injection via shell metacharacters.",
			Remediation: "Set shell=False and pass command arguments as an array: subprocess.run(['ls', '-la'], shell=False).",
		},
		{
			ID:          GenerateDeterministicUUID("PY-MUTABLE-DEFAULT-ARGUMENT"),
			Code:        "PY-MUTABLE-DEFAULT-ARGUMENT",
			Name:        "Mutable Object Used as Default Function Argument",
			Category:    "PYTHON_CODE_QUALITY",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-1188",
			RegexRule:   `def\s+\w+\s*\([^)]*=\s*(?:\[\]|\{\}|set\(\))`,
			Description: "Default argument values are evaluated once at function definition time, sharing state across all function calls.",
			Remediation: "Use None as the default argument value and initialize the mutable object inside the function body.",
		},
		{
			ID:          GenerateDeterministicUUID("PY-FLASK-DEBUG-PRODUCTION"),
			Code:        "PY-FLASK-DEBUG-PRODUCTION",
			Name:        "Flask Application Started with debug=True",
			Category:    "PYTHON_SECURITY",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-489",
			RegexRule:   `app\.run\s*\([^)]*debug\s*=\s*True`,
			Description: "Running Flask with debug=True enables the interactive Werkzeug debugger console, allowing arbitrary remote code execution.",
			Remediation: "Ensure debug=False in production and run Flask behind a WSGI server (Gunicorn / uWSGI).",
		},
		{
			ID:          GenerateDeterministicUUID("PY-DJANGO-DEBUG-TRUE"),
			Code:        "PY-DJANGO-DEBUG-TRUE",
			Name:        "Django DEBUG Setting Hardcoded to True",
			Category:    "PYTHON_SECURITY",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-489",
			RegexRule:   `(?m)^DEBUG\s*=\s*True`,
			Description: "Running Django with DEBUG=True leaks sensitive environment variables, database queries, and stack traces on 500 errors.",
			Remediation: "Read DEBUG from environment variables: DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'.",
		},
		{
			ID:          GenerateDeterministicUUID("PY-INSECURE-TEMPFILE-MKTEMP"),
			Code:        "PY-INSECURE-TEMPFILE-MKTEMP",
			Name:        "Use of Insecure tempfile.mktemp()",
			Category:    "PYTHON_SECURITY",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-377",
			RegexRule:   `tempfile\.mktemp\s*\(`,
			Description: "tempfile.mktemp() is vulnerable to symlink race conditions (TOCTOU) between filename generation and creation.",
			Remediation: "Use tempfile.NamedTemporaryFile() or tempfile.mkstemp() instead.",
		},
		{
			ID:          GenerateDeterministicUUID("PY-SQL-FORMAT-STRING-DJANGO-RAW"),
			Code:        "PY-SQL-FORMAT-STRING-DJANGO-RAW",
			Name:        "SQL Injection via Django raw() or extra() with Format Strings",
			Category:    "PYTHON_SECURITY",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-89",
			RegexRule:   `(?i)\.(?:raw|extra)\s*\(\s*(?:f["'].*\{|["'].*%s.*["']\s*%)`,
			Description: "Formatting strings into Django ORM raw() or extra() queries bypassing parameterized query safeguards.",
			Remediation: "Pass query parameters as a list/tuple to raw(sql, [param1, param2]).",
		},
		{
			ID:          GenerateDeterministicUUID("PY-BARE-EXCEPT-CLAUSE"),
			Code:        "PY-BARE-EXCEPT-CLAUSE",
			Name:        "Bare except: Clause Catching SystemExit & KeyboardInterrupt",
			Category:    "PYTHON_BEST_PRACTICE",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-396",
			RegexRule:   `(?m)^\s*except\s*:`,
			Description: "A bare 'except:' catches BaseException including KeyboardInterrupt and SystemExit, making processes unkillable.",
			Remediation: "Catch specific exception classes: except Exception as e: or except (ValueError, KeyError):.",
		},
		{
			ID:          GenerateDeterministicUUID("PY-ASSERT-USED-FOR-VALIDATION"),
			Code:        "PY-ASSERT-USED-FOR-VALIDATION",
			Name:        "Use of assert for Security or Authorization Checks",
			Category:    "PYTHON_SECURITY",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-617",
			RegexRule:   `(?i)assert\s+(?:is_admin|user\.|permission|role|auth)`,
			Description: "assert statements are completely stripped from bytecode when Python runs with optimization flags (python -O).",
			Remediation: "Use explicit conditional checks: if not is_admin: raise PermissionError().",
		},
		{
			ID:          GenerateDeterministicUUID("PY-REQUESTS-VERIFY-FALSE"),
			Code:        "PY-REQUESTS-VERIFY-FALSE",
			Name:        "requests.get/post with verify=False",
			Category:    "PYTHON_SECURITY",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-295",
			RegexRule:   `requests\.(?:get|post|put|delete|patch|request)\s*\([^)]*verify\s*=\s*False`,
			Description: "Disabling SSL/TLS certificate verification in requests exposes outbound HTTP calls to interception.",
			Remediation: "Remove verify=False or provide a path to a trusted CA bundle.",
		},
		{
			ID:          GenerateDeterministicUUID("PY-PARAMIKO-MISSING-HOST-KEY-POLICY"),
			Code:        "PY-PARAMIKO-MISSING-HOST-KEY-POLICY",
			Name:        "Paramiko AutoAddPolicy Disabling Host Key Verification",
			Category:    "PYTHON_SECURITY",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-295",
			RegexRule:   `paramiko\.AutoAddPolicy\s*\(`,
			Description: "AutoAddPolicy automatically accepts unknown SSH host keys without verification, enabling SSH MitM attacks.",
			Remediation: "Use RejectPolicy() or WarningPolicy() with known_hosts pre-populated.",
		},
		{
			ID:          GenerateDeterministicUUID("PY-JINJA2-AUTOESCAPE-FALSE"),
			Code:        "PY-JINJA2-AUTOESCAPE-FALSE",
			Name:        "Jinja2 Template Environment with autoescape=False",
			Category:    "PYTHON_SECURITY",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-79",
			RegexRule:   `jinja2\.Environment\s*\([^)]*autoescape\s*=\s*False`,
			Description: "Disabling autoescape in Jinja2 template rendering enables stored and reflected Cross-Site Scripting (XSS).",
			Remediation: "Enable autoescape: Environment(autoescape=select_autoescape(['html', 'xml'])).",
		},
		{
			ID:          GenerateDeterministicUUID("PY-HASH-MD5-USAGE"),
			Code:        "PY-HASH-MD5-USAGE",
			Name:        "Use of hashlib.md5() or hashlib.sha1()",
			Category:    "PYTHON_CRYPTO",
			Language:    "PYTHON",
			PathPattern: "*.py",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-328",
			RegexRule:   `hashlib\.(?:md5|sha1)\s*\(`,
			Description: "MD5 and SHA-1 algorithms are vulnerable to practical collision attacks.",
			Remediation: "Use hashlib.sha256() or hashlib.sha3_256().",
		},
	}
}
