package catalog

import "github.com/scandrix/backend/pkg/models"

// GetTypeScriptRules returns 15 TypeScript and JavaScript security and quality rules.
func GetTypeScriptRules() []RuleDefinition {
	return []RuleDefinition{
		{
			ID:          GenerateDeterministicUUID("TS-DANGEROUSLY-SET-INNER-HTML"),
			Code:        "TS-DANGEROUSLY-SET-INNER-HTML",
			Name:        "Direct Use of dangerouslySetInnerHTML in React",
			Category:    "TYPESCRIPT_SECURITY",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,tsx,js,jsx}",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-79",
			RegexRule:   `dangerouslySetInnerHTML\s*=\s*\{\s*\{\s*__html:\s*(?:req|input|data|props\.\w+)\s*\}\s*\}`,
			Description: "Passing unescaped user content directly to dangerouslySetInnerHTML introduces DOM XSS.",
			Remediation: "Sanitize user HTML strings using DOMPurify.sanitize() before setting innerHTML.",
		},
		{
			ID:          GenerateDeterministicUUID("TS-EVAL-USAGE"),
			Code:        "TS-EVAL-USAGE",
			Name:        "Use of eval() or Function() Constructor",
			Category:    "TYPESCRIPT_SECURITY",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,tsx,js,jsx}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-95",
			RegexRule:   `(?i)\b(?:eval|Function)\s*\(\s*(?:req|input|param|\+.*)`,
			Description: "Dynamic code execution via eval() allows attackers to execute arbitrary JavaScript within the runtime environment.",
			Remediation: "Use JSON.parse() for structured data and avoid dynamic string code evaluation.",
		},
		{
			ID:          GenerateDeterministicUUID("TS-PROTOTYPE-POLLUTION"),
			Code:        "TS-PROTOTYPE-POLLUTION",
			Name:        "Prototype Pollution via __proto__ or Object.assign",
			Category:    "TYPESCRIPT_SECURITY",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,tsx,js,jsx}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-1321",
			RegexRule:   `(?i)\[["']__proto__["']\]|Object\.assign\s*\(\s*\{\}\s*,\s*req\.body\s*\)`,
			Description: "Assigning unbounded recursive user objects can modify Object.prototype, affecting all objects across the Node.js process.",
			Remediation: "Use Object.create(null) for dictionary maps or sanitize keys against '__proto__', 'constructor', and 'prototype'.",
		},
		{
			ID:          GenerateDeterministicUUID("TS-EXPRESS-BODYPARSER-UNLIMITED"),
			Code:        "TS-EXPRESS-BODYPARSER-UNLIMITED",
			Name:        "Express Body Parser without Payload Size Limits",
			Category:    "TYPESCRIPT_SECURITY",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,js}",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-400",
			RegexRule:   `bodyParser\.(?:json|urlencoded)\s*\(\s*\)|express\.(?:json|urlencoded)\s*\(\s*\)`,
			Description: "Enabling body-parser without explicit { limit: '100kb' } permits Denial of Service via large HTTP request payloads.",
			Remediation: "Configure explicit body size limits: express.json({ limit: '1mb' }).",
		},
		{
			ID:          GenerateDeterministicUUID("TS-REDOS-REGEXP-NESTED-QUANTIFIER"),
			Code:        "TS-REDOS-REGEXP-NESTED-QUANTIFIER",
			Name:        "Regular Expression Denial of Service (ReDoS) Risk",
			Category:    "TYPESCRIPT_PERFORMANCE",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,tsx,js,jsx}",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-1333",
			RegexRule:   `new\s+RegExp\([^)]*(?:\([a-z0-9\-_|]+\+\)\+|\([a-z0-9\-_|]+\*\)\*)`,
			Description: "Nested quantifiers in regular expressions cause catastrophic backtracking on non-matching inputs, freezing the Node.js event loop.",
			Remediation: "Simplify regex patterns, avoid nested quantifiers, or use linear-time regex engines like RE2.",
		},
		{
			ID:          GenerateDeterministicUUID("TS-INSECURE-CHILD-PROCESS-EXEC"),
			Code:        "TS-INSECURE-CHILD-PROCESS-EXEC",
			Name:        "OS Command Injection via child_process.exec()",
			Category:    "TYPESCRIPT_SECURITY",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,js}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-78",
			RegexRule:   `child_process\.exec\s*\(\s*(?:` + "`" + `.*` + "`" + `|\w+\s*\+)`,
			Description: "child_process.exec() passes commands through a system shell, enabling command injection via metacharacters (; | &).",
			Remediation: "Use child_process.execFile() or child_process.spawn() with argument arrays.",
		},
		{
			ID:          GenerateDeterministicUUID("TS-CRYPTO-CREATE-CIPHER-DEPRECATED"),
			Code:        "TS-CRYPTO-CREATE-CIPHER-DEPRECATED",
			Name:        "Use of Deprecated crypto.createCipher()",
			Category:    "TYPESCRIPT_CRYPTO",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,js}",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-327",
			RegexRule:   `crypto\.createCipher\s*\(`,
			Description: "crypto.createCipher() uses weak key derivation (MD5 without salt).",
			Remediation: "Use crypto.createCipheriv() with a cryptographically random initialization vector (IV) and AES-GCM.",
		},
		{
			ID:          GenerateDeterministicUUID("TS-NODE-TLS-REJECT-UNAUTHORIZED"),
			Code:        "TS-NODE-TLS-REJECT-UNAUTHORIZED",
			Name:        "NODE_TLS_REJECT_UNAUTHORIZED Disabled",
			Category:    "TYPESCRIPT_SECURITY",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,js}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-295",
			RegexRule:   `process\.env\.NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"]0['"]`,
			Description: "Setting NODE_TLS_REJECT_UNAUTHORIZED='0' disables certificate validation globally for all HTTPS requests in the Node process.",
			Remediation: "Never disable TLS rejection in code. Install root CA certificates into the environment if testing with self-signed certs.",
		},
		{
			ID:          GenerateDeterministicUUID("TS-UNUSED-PROMISE-RETURN"),
			Code:        "TS-UNUSED-PROMISE-RETURN",
			Name:        "Floating Promise Without Await or Catch Handler",
			Category:    "TYPESCRIPT_RELIABILITY",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,tsx}",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-391",
			RegexRule:   `(?m)^\s*(?:async\w+|fetch|axios\.\w+|db\.\w+)\(.*\);`,
			Description: "Executing asynchronous promise-returning functions without await or .catch() triggers unhandled promise rejection crashes.",
			Remediation: "Add await, return the promise, or attach .catch(err => ...).",
		},
		{
			ID:          GenerateDeterministicUUID("TS-LOCALSTORAGE-AUTH-TOKEN"),
			Code:        "TS-LOCALSTORAGE-AUTH-TOKEN",
			Name:        "Storing Authentication Tokens in localStorage",
			Category:    "TYPESCRIPT_SECURITY",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,tsx,js,jsx}",
			Severity:    models.SeverityMedium,
			CWE:         "CWE-312",
			RegexRule:   `localStorage\.setItem\s*\(\s*["'](?:token|auth_token|jwt|access_token|refresh_token)["']`,
			Description: "Storing JWTs or authentication tokens in localStorage makes them accessible to any XSS payload on the page.",
			Remediation: "Store session tokens in httpOnly, Secure, SameSite cookies.",
		},
		{
			ID:          GenerateDeterministicUUID("TS-NON-STRICT-EQUALITY"),
			Code:        "TS-NON-STRICT-EQUALITY",
			Name:        "Use of Loose Equality Operator (== or !=)",
			Category:    "TYPESCRIPT_CODE_QUALITY",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,tsx,js,jsx}",
			Severity:    models.SeverityLow,
			CWE:         "CWE-1188",
			RegexRule:   `\s+(?:==|!=)\s+`,
			Description: "Loose equality triggers unexpected JavaScript type coercion ('0' == 0, null == undefined).",
			Remediation: "Use strict equality operators (=== and !==).",
		},
		{
			ID:          GenerateDeterministicUUID("TS-JWT-HARDCODED-SECRET"),
			Code:        "TS-JWT-HARDCODED-SECRET",
			Name:        "Hardcoded Secret in jwt.sign() or jwt.verify()",
			Category:    "TYPESCRIPT_SECURITY",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,js}",
			Severity:    models.SeverityCritical,
			CWE:         "CWE-798",
			RegexRule:   `jwt\.(?:sign|verify)\s*\([^,]+,\s*["'][^"']{4,32}["']`,
			Description: "Hardcoding JWT signing secret strings directly into code compromises signature integrity.",
			Remediation: "Load the secret from process.env.JWT_SECRET or use an asymmetric private key.",
		},
		{
			ID:          GenerateDeterministicUUID("TS-ANY-TYPE-ABUSE"),
			Code:        "TS-ANY-TYPE-ABUSE",
			Name:        "Excessive Use of 'any' Type in TypeScript Interface",
			Category:    "TYPESCRIPT_CODE_QUALITY",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,tsx}",
			Severity:    models.SeverityLow,
			CWE:         "CWE-1188",
			RegexRule:   `:\s*any\s*(?:\[\])?\s*[;,]`,
			Description: "Using 'any' turns off TypeScript type checking and allows runtime type errors to escape compiler validation.",
			Remediation: "Replace 'any' with 'unknown', a strict generic type, or explicit interface definition.",
		},
		{
			ID:          GenerateDeterministicUUID("TS-MATH-RANDOM-FOR-SECURITY"),
			Code:        "TS-MATH-RANDOM-FOR-SECURITY",
			Name:        "Use of Math.random() in Security Context",
			Category:    "TYPESCRIPT_SECURITY",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,tsx,js,jsx}",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-338",
			RegexRule:   `(?i)Math\.random\(\).*(?:token|secret|password|session|csrf|salt)`,
			Description: "Math.random() is cryptographically weak and predictable.",
			Remediation: "Use crypto.randomBytes() or crypto.getRandomValues().",
		},
		{
			ID:          GenerateDeterministicUUID("TS-EXPRESS-CORS-ORIGIN-TRUE"),
			Code:        "TS-EXPRESS-CORS-ORIGIN-TRUE",
			Name:        "CORS origin: true Reflecting Any Inbound Origin",
			Category:    "TYPESCRIPT_SECURITY",
			Language:    "TYPESCRIPT",
			PathPattern: "*.{ts,js}",
			Severity:    models.SeverityHigh,
			CWE:         "CWE-942",
			RegexRule:   `cors\s*\(\s*\{\s*origin\s*:\s*true\s*,\s*credentials\s*:\s*true\s*\}`,
			Description: "Setting origin: true dynamically reflects the requesting Origin header, completely bypassing CORS boundaries for credentialed requests.",
			Remediation: "Provide an explicit array of approved origin URLs.",
		},
	}
}
