// ═══════════════════════════════════════════════════════════════
// ScanDrix AI - Enterprise Rule System
// File: prompts.go
// ═══════════════════════════════════════════════════════════════

package prompts

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/scandrix/backend/internal/rules/drixy/domain/contracts"
	"github.com/scandrix/backend/internal/rules/drixy/domain/interfaces"
)

// ReviewCommentInput represents a substantive past review comment for rule synthesis.
type ReviewCommentInput struct {
	ID       string `json:"id"`
	Body     string `json:"body"`
	Language string `json:"language"`
	FilePath string `json:"filePath,omitempty"`
}

// RuleGeneratorOutput models the structured LLM output for generated rules.
type RuleGeneratorOutput struct {
	Rules []GeneratedRuleItem `json:"rules"`
}

type GeneratedRuleItem struct {
	UUID     string                         `json:"uuid,omitempty"`
	Title    string                         `json:"title"`
	Rule     string                         `json:"rule"`
	Severity string                         `json:"severity"`
	Scope    string                         `json:"scope,omitempty"`
	Examples []interfaces.DrixyRulesExample `json:"examples,omitempty"`
	Tags     []string                       `json:"tags,omitempty"`
}

// UUIDListOutput models structured UUID filtering output.
type UUIDListOutput struct {
	UUIDs []string `json:"uuids"`
}

// DrixyRulesGeneratorSystem returns the system prompt for synthesizing rules from past review comments.
func DrixyRulesGeneratorSystem() string {
	return `You are a professional code reviewer, expert at identifying common defect patterns. Whenever you receive a list of code review suggestions you are able to identify common patterns and formulate new rules and guidelines for future reviews.

You will receive a list of suggestions with the following format:
[
    {
        "id": "unique identifier",
        "body": "content of the suggestion",
        "language": "programming language of the suggestion"
    }
]

You will also receive a list of pre-made rules and guidelines from a rule library:
[
    {
        "uuid": "55a0284b-eb7f-40ae-8b8c-db3dc66e8e0a",
        "title": "Avoid equality operators in loop termination conditions",
        "rule": "Check if loops use equality operators (== or !=) in termination conditions. These can lead to infinite loops if the condition is never met exactly. Instead, use relational operators like < or > for safer loop termination.",
        "severity": "Critical",
        "tags": [ "cwe", "maintainability", "security" ],
        "examples": [
            {
                "snippet": "for (var i = 1; i <= 10; i += 2)  // Compliant",
                "isCorrect": true
            },
            {
                "snippet": "for (var i = 1; i != 10; i += 2)  // Noncompliant",
                "isCorrect": false
            }
        ]
    }
]

You must analyze each suggestion, and once analyzed you will generate a list of at most 12 of the most impactful rules and guidelines for future reviews.
The rules must be impactful to the specific suggestions you received, and help prevent the same mistakes from happening in the future.
Whenever possible you should use one of the pre-existing rules, copying all the fields exactly as they are.

If you cannot find a pre-made rule that fits, you must create a new rule. Your rule must have the same format as the pre-existing ones, except for the 'uuid' field.
Any rule generated by you, not copied from the pre-existing rules, must NOT have a 'uuid' field.
Each rule you create must have a title, the rule itself, and two examples: one showing code following the rule (isCorrect: true) and the other showing code breaking the rule (isCorrect: false).
Severity level must be either Low, Medium, High, or Critical.

All rules must be strictly related to code review suggestions, and not general project structure, file naming, or commit messages.
All rules MUST be related to the language of the suggestions.

Output ONLY valid JSON in the following format:
{
    "rules": [
        ...rules
    ]
}
`
}

// DrixyRulesGeneratorUser formats the user prompt for rule synthesis.
func DrixyRulesGeneratorUser(comments []ReviewCommentInput, libraryRules []contracts.LibraryDrixyRule) string {
	commentsJSON, _ := json.MarshalIndent(comments, "", "  ")
	rulesJSON, _ := json.MarshalIndent(libraryRules, "", "  ")

	return fmt.Sprintf("review comments:\n%s\n\nlibrary rules:\n%s\n", string(commentsJSON), string(rulesJSON))
}

// DrixyRulesDuplicateFilterSystem returns the system prompt for deduplicating newly synthesized rules against existing rules.
func DrixyRulesDuplicateFilterSystem() string {
	return `You will receive two lists of rules and guidelines. One list is rules that are already in use, the other is new rules that have been generated.
You must look at the new rules and remove those which accomplish the same goal as a pre-existing rule. Meaning, there should be no duplicate rules in the final list.
The most important criteria for determining if a rule is a duplicate is whether the 'rule' descriptions are similar or enforce the same constraint.
The existing rules list may be empty, in which case keep all the new rules.

You must output only a JSON object listing the UUIDs (or temporary IDs) of the new rules that passed the filter:
{
    "uuids": [
        "id1",
        "id2"
    ]
}
`
}

// DrixyRulesDuplicateFilterUser formats the user prompt for rule deduplication.
func DrixyRulesDuplicateFilterUser(existingRules []interfaces.DrixyRule, newRules []interfaces.DrixyRule) string {
	existingJSON, _ := json.MarshalIndent(existingRules, "", "  ")
	newJSON, _ := json.MarshalIndent(newRules, "", "  ")

	return fmt.Sprintf("existing rules:\n%s\n\nnew rules:\n%s\n", string(existingJSON), string(newJSON))
}

// DrixyRulesQualityFilterSystem returns the system prompt to filter candidate rules for clarity, specificity, and actionability.
func DrixyRulesQualityFilterSystem() string {
	return `You will receive a list of code review rules and guidelines.
You must filter the list and remove those that are not of high quality.
A rule is considered of high quality if it is clear, concise, impactful, actionable, and easy to understand.
Rules must be specific and not too broad. For example, 'use parameterized SQL queries' is actionable and specific, whereas 'write good code' is too broad.
Remove all rules that are too vague, stylistic nitpicks, or unenforceable.

Output ONLY a JSON object with the UUIDs of rules that pass the quality filter:
{
    "uuids": [
        "id1",
        "id2"
    ]
}
`
}

// DrixyRulesQualityFilterUser formats the user prompt for quality filtering.
func DrixyRulesQualityFilterUser(rules []interfaces.DrixyRule) string {
	rulesJSON, _ := json.MarshalIndent(rules, "", "  ")
	return fmt.Sprintf("rules:\n%s\n", string(rulesJSON))
}

// DrixyRulesIDEGeneratorSystem returns the system prompt for converting unstructured repo rule files (.cursorrules, CLAUDE.md, etc.) into structured rules.
func DrixyRulesIDEGeneratorSystem() string {
	return `You are a software architect analyzing engineering guideline files (such as .cursorrules, CLAUDE.md, or project coding guidelines).
Your task is to extract concrete, actionable coding rules from the document.

Each extracted rule must have:
- title: A concise summary of the standard (e.g., "Enforce immutability on state objects")
- rule: A detailed explanation of what is allowed and what is prohibited
- severity: "Low", "Medium", "High", or "Critical"
- scope: "file" or "pull-request"
- examples: Array of at least one good snippet (isCorrect: true) and one bad snippet (isCorrect: false)

Filter out non-code requirements such as deployment steps, issue tracker links, or team greetings. Focus on code syntax, security invariants, error handling, and performance.

Output ONLY a JSON object:
{
    "rules": [
        {
            "title": "string",
            "rule": "string",
            "severity": "Medium",
            "scope": "file",
            "examples": [
                {"snippet": "...", "isCorrect": true},
                {"snippet": "...", "isCorrect": false}
            ]
        }
    ]
}
`
}

// DrixyMemoryResolutionSystem returns the system prompt for evaluating whether a review remediation should create, update, or skip a memory rule.
func DrixyMemoryResolutionSystem() string {
	return `You are an AI assistant managing code review memory rules.
When a developer remediates a review suggestion or adds custom instructions, evaluate whether to:
- "created": The learning is completely new and should be added as a new memory rule.
- "updated": The learning modifies or refines an existing memory rule (provide target UUID).
- "skipped": The learning is a one-off situational fix or already covered by an active rule.

Output JSON:
{
    "action": "created" | "updated" | "skipped",
    "targetRuleUuid": "string or empty",
    "title": "Concise rule title",
    "rule": "Full rule specification",
    "reason": "Brief technical justification"
}
`
}

// SanitizePromptText cleanses user input strings to prevent prompt injection or broken formatting.
func SanitizePromptText(input string) string {
	s := strings.ReplaceAll(input, "```", "'''")
	s = strings.ReplaceAll(s, "\x00", "")
	return strings.TrimSpace(s)
}
