package clireview

import (
	"fmt"
	"strings"
	"time"
)

// TraceContextService manages decision tracing and PR comment integration.
type TraceContextService struct {
	sessionStore *SessionStore
}

// NewTraceContextService creates an initialized trace context service.
func NewTraceContextService(sessionStore *SessionStore) *TraceContextService {
	if sessionStore == nil {
		sessionStore = NewSessionStore()
	}
	return &TraceContextService{
		sessionStore: sessionStore,
	}
}

// BuildContextPack constructs a comprehensive context bundle from a session.
func (tcs *TraceContextService) BuildContextPack(sessionID string) (*TraceContextPack, error) {
	capture, ok := tcs.sessionStore.GetCapture(sessionID)
	if !ok {
		return &TraceContextPack{
			SessionID: sessionID,
			Summary:   "No active session capture found for " + sessionID,
			CreatedAt: time.Now().UTC(),
		}, nil
	}

	pack := &TraceContextPack{
		SessionID: sessionID,
		Decisions: capture.ClassifiedDecisions,
		Summary:   capture.Summary,
		CreatedAt: time.Now().UTC(),
	}

	for i, d := range capture.ClassifiedDecisions {
		pack.Branches = append(pack.Branches, TraceDecisionBranch{
			ID:        fmt.Sprintf("%s-branch-%d", sessionID, i+1),
			Branch:    "main",
			Decision:  d.Decision,
			Type:      string(d.Type),
			Rationale: d.Rationale,
			Timestamp: time.Now().UTC(),
		})
	}

	return pack, nil
}

// FormatTracePrComment renders markdown for posting to a pull request.
func (tcs *TraceContextService) FormatTracePrComment(pack *TraceContextPack) string {
	if pack == nil || len(pack.Decisions) == 0 {
		return "### 🛡️ ScanDrix Trace\n\nNo explicit architectural decisions recorded for this PR."
	}

	var sb strings.Builder
	sb.WriteString("### 🛡️ ScanDrix Trace — Autonomous Decision Context\n\n")
	sb.WriteString("The following architectural decisions and conventions were recorded during this session:\n\n")

	sb.WriteString("| Type | Decision | Origin | Confidence |\n")
	sb.WriteString("| :--- | :--- | :--- | :--- |\n")

	for _, d := range pack.Decisions {
		origin := string(d.Origin)
		if origin == "" {
			origin = "collaborative"
		}
		conf := fmt.Sprintf("%.0f%%", d.Confidence*100)
		sb.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n", d.Type, d.Decision, origin, conf))
	}

	sb.WriteString("\n*Automated trace context generated by ScanDrix AI Assurance Engine.*")
	return sb.String()
}
