package formatters

import (
	"fmt"
	"io"
	"strings"

	"github.com/scandrix/backend/internal/cli/types"
)

// MarkdownFormatter outputs review results formatted in GitHub/GitLab markdown.
type MarkdownFormatter struct {
	IncludeDetails bool
}

// NewMarkdownFormatter creates a new MarkdownFormatter instance.
func NewMarkdownFormatter(includeDetails bool) *MarkdownFormatter {
	return &MarkdownFormatter{
		IncludeDetails: includeDetails,
	}
}

func (m *MarkdownFormatter) getSeverityEmoji(sev types.Severity) string {
	switch sev {
	case types.SeverityCritical:
		return "🔴"
	case types.SeverityError:
		return "❌"
	case types.SeverityWarning:
		return "⚠️"
	case types.SeverityInfo:
		return "ℹ️"
	default:
		return "⚪"
	}
}

// Format formats the ReviewResult into GitHub-flavored markdown.
func (m *MarkdownFormatter) Format(w io.Writer, result *types.ReviewResult) error {
	var sb strings.Builder

	sb.WriteString("# ScanDrix Code Review Report\n\n")

	// Overview
	sb.WriteString("## Summary\n\n")
	sb.WriteString(fmt.Sprintf("- **Status:** `%s`\n", strings.ToUpper(result.Status)))
	sb.WriteString(fmt.Sprintf("- **Files Analyzed:** %d\n", result.FilesAnalyzed))
	sb.WriteString(fmt.Sprintf("- **Duration:** %dms\n", result.DurationMs))

	if result.GitContext != nil && result.GitContext.Branch != "" {
		sb.WriteString(fmt.Sprintf("- **Branch:** `%s` (`%s`)\n",
			result.GitContext.Branch,
			result.GitContext.HeadSHA[:min(8, len(result.GitContext.HeadSHA))],
		))
	}
	sb.WriteString("\n")

	// Breakdown Table
	sb.WriteString("| Severity | Count |\n")
	sb.WriteString("| :--- | :---: |\n")
	sb.WriteString(fmt.Sprintf("| 🔴 Critical | %d |\n", result.Stats.CriticalCount))
	sb.WriteString(fmt.Sprintf("| ❌ Error | %d |\n", result.Stats.ErrorCount))
	sb.WriteString(fmt.Sprintf("| ⚠️ Warning | %d |\n", result.Stats.WarningCount))
	sb.WriteString(fmt.Sprintf("| ℹ️ Info | %d |\n", result.Stats.InfoCount))
	sb.WriteString(fmt.Sprintf("| **Total** | **%d** |\n\n", result.Stats.TotalIssues))

	if len(result.Issues) == 0 {
		sb.WriteString("### ✓ All clear! No code issues were detected.\n\n")
		_, err := io.WriteString(w, sb.String())
		return err
	}

	sb.WriteString("## Findings\n\n")

	// Group issues by file
	issuesByFile := make(map[string][]types.ReviewIssue)
	var fileOrder []string
	for _, issue := range result.Issues {
		if _, exists := issuesByFile[issue.File]; !exists {
			fileOrder = append(fileOrder, issue.File)
		}
		issuesByFile[issue.File] = append(issuesByFile[issue.File], issue)
	}

	for _, file := range fileOrder {
		issues := issuesByFile[file]
		sb.WriteString(fmt.Sprintf("### `%s` (%d findings)\n\n", file, len(issues)))

		for _, issue := range issues {
			emoji := m.getSeverityEmoji(issue.Severity)
			sevName := strings.ToUpper(string(issue.Severity))

			lineStr := ""
			if issue.Line > 0 {
				lineStr = fmt.Sprintf(" (Line %d)", issue.Line)
			}

			sb.WriteString(fmt.Sprintf("#### %s **%s**%s\n\n", emoji, sevName, lineStr))

			if issue.Category != "" {
				sb.WriteString(fmt.Sprintf("**Category:** `%s`  \n", issue.Category))
			}
			if issue.RuleID != "" {
				sb.WriteString(fmt.Sprintf("**Rule:** `%s`  \n", issue.RuleID))
			}

			sb.WriteString(fmt.Sprintf("\n%s\n\n", issue.Message))

			if issue.Suggestion != "" {
				sb.WriteString("**Suggestion:**\n")
				sb.WriteString("```suggestion\n")
				sb.WriteString(issue.Suggestion)
				sb.WriteString("\n```\n\n")
			} else if issue.Recommendation != "" {
				sb.WriteString(fmt.Sprintf("> **Recommendation:** %s\n\n", issue.Recommendation))
			}

			if issue.Fixable && issue.Fix != nil && issue.Fix.NewCode != "" {
				sb.WriteString("<details><summary>Suggested Fix</summary>\n\n")
				sb.WriteString("```diff\n")
				for _, l := range strings.Split(issue.Fix.OldCode, "\n") {
					if l != "" {
						sb.WriteString("- " + l + "\n")
					}
				}
				for _, l := range strings.Split(issue.Fix.NewCode, "\n") {
					if l != "" {
						sb.WriteString("+ " + l + "\n")
					}
				}
				sb.WriteString("```\n\n</details>\n\n")
			}

			if m.IncludeDetails && issue.HunkContext != "" {
				sb.WriteString("<details><summary>Context Diff</summary>\n\n")
				sb.WriteString("```diff\n")
				sb.WriteString(issue.HunkContext)
				sb.WriteString("\n```\n\n</details>\n\n")
			}

			sb.WriteString("---\n\n")
		}
	}

	sb.WriteString("\n*Report generated by [ScanDrix](https://scandrix.dev)*\n")

	_, err := io.WriteString(w, sb.String())
	return err
}
