package usecases

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"log/slog"
	"regexp"
	"strings"

	"github.com/scandrix/backend/internal/platform/domain/contracts"
	"github.com/scandrix/backend/internal/platform/domain/types"
)

// TriggerBusinessValidationInput defines user-submitted parameters for verifying PR diffs against acceptance criteria.
type TriggerBusinessValidationInput struct {
	PRURL        string `json:"prUrl,omitempty"`
	PRNumber     *int   `json:"prNumber,omitempty"`
	RepositoryID string `json:"repositoryId,omitempty"`
	Repository   string `json:"repository,omitempty"`
	TaskURL      string `json:"taskUrl,omitempty"`
	TaskID       string `json:"taskId,omitempty"`
	Diff         string `json:"diff,omitempty"`
}

const (
	BusinessValidationModePullRequest = "pull_request"
	BusinessValidationModeLocalDiff   = "local_diff"
)

// TriggerBusinessValidationResult conveys the validation report generated by Drixy.
type TriggerBusinessValidationResult struct {
	Accepted       bool   `json:"accepted"`
	Mode           string `json:"mode"`
	Command        string `json:"command"`
	PRNumber       *int   `json:"prNumber,omitempty"`
	PRURL          string `json:"prUrl,omitempty"`
	RepositoryID   string `json:"repositoryId,omitempty"`
	RepositoryName string `json:"repositoryName,omitempty"`
	TaskReference  string `json:"taskReference,omitempty"`
	Result         string `json:"result"`
}

// BusinessValidationRepositoryContext captures repository identity and default branch.
type BusinessValidationRepositoryContext struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Owner         string `json:"owner,omitempty"`
	DefaultBranch string `json:"defaultBranch,omitempty"`
}

// BusinessSignals encapsulates detected tickets, links, and keywords.
type BusinessSignals struct {
	TicketKeys          []string `json:"ticketKeys"`
	TaskLinks           []string `json:"taskLinks"`
	RequirementKeywords []string `json:"requirementKeywords"`
}

// BusinessValidationExecutionContext holds contextual diff and requirement information.
type BusinessValidationExecutionContext struct {
	Mode                   string                               `json:"mode"`
	PullRequestDescription string                               `json:"pullRequestDescription,omitempty"`
	Repository             *BusinessValidationRepositoryContext `json:"repository,omitempty"`
	PRDiff                 string                               `json:"prDiff,omitempty"`
	PRNumber               int                                  `json:"prNumber,omitempty"`
	PRURL                  string                               `json:"prUrl,omitempty"`
	HeadRef                string                               `json:"headRef,omitempty"`
	BaseRef                string                               `json:"baseRef,omitempty"`
}

// BusinessRulesPrepareContext models the structured context passed to the validation agent.
type BusinessRulesPrepareContext struct {
	UserQuestion           string                               `json:"userQuestion"`
	TaskReference          string                               `json:"taskReference,omitempty"`
	TaskID                 string                               `json:"taskId,omitempty"`
	TaskURL                string                               `json:"taskUrl,omitempty"`
	PullRequestDescription string                               `json:"pullRequestDescription,omitempty"`
	PlatformType           string                               `json:"platformType,omitempty"`
	BusinessSignals        BusinessSignals                      `json:"businessSignals"`
	Repository             *BusinessValidationRepositoryContext `json:"repository,omitempty"`
	DefaultBranch          string                               `json:"defaultBranch,omitempty"`
	PRDiff                 string                               `json:"prDiff,omitempty"`
	PullRequest            map[string]any                       `json:"pullRequest,omitempty"`
	PullRequestNumber      int                                  `json:"pullRequestNumber,omitempty"`
	HeadRef                string                               `json:"headRef,omitempty"`
	BaseRef                string                               `json:"baseRef,omitempty"`
}

// IBusinessRulesValidationAgent runs the autonomous business requirements audit.
type IBusinessRulesValidationAgent interface {
	ValidateBusinessRules(ctx context.Context, orgData types.OrganizationAndTeamData, execCtx BusinessValidationExecutionContext, command string) (string, error)
}

// IIntegrationRepositoryProvider retrieves configured repositories for an organization and team.
type IIntegrationRepositoryProvider interface {
	GetConfiguredRepositories(ctx context.Context, orgData types.OrganizationAndTeamData) ([]*types.Repositories, error)
}

// TriggerBusinessValidationUseCase translates trigger-business-validation.use-case.ts.
// Performs 1:1 validation of PR diffs or local git diffs against Jira / Linear / Azure Boards acceptance criteria.
type TriggerBusinessValidationUseCase struct {
	codeManagementService contracts.ICodeManagementService
	integrationRepoSvc    IIntegrationRepositoryProvider
	agent                 IBusinessRulesValidationAgent
	logger                *slog.Logger
}

const (
	MaxSignalSourceLength = 20000
)

var requirementKeywords = []string{
	"requirement",
	"acceptance criteria",
	"user story",
	"given",
	"when",
	"then",
}

var (
	ticketKeyRegex = regexp.MustCompile(`[A-Z]{2,}-\d+`)
	taskLinkRegex  = regexp.MustCompile(`https?://[^\s)>\]"']+`)
)

// NewTriggerBusinessValidationUseCase constructs a new instance.
func NewTriggerBusinessValidationUseCase(
	codeManagementService contracts.ICodeManagementService,
	agent IBusinessRulesValidationAgent,
) *TriggerBusinessValidationUseCase {
	return &TriggerBusinessValidationUseCase{
		codeManagementService: codeManagementService,
		agent:                 agent,
		logger:                slog.Default(),
	}
}

// SetIntegrationRepositoryProvider sets optional configured repositories provider.
func (uc *TriggerBusinessValidationUseCase) SetIntegrationRepositoryProvider(prov IIntegrationRepositoryProvider) {
	uc.integrationRepoSvc = prov
}

// Execute parses input, validates criteria, resolves PR/diff context, and runs business rules validation.
func (uc *TriggerBusinessValidationUseCase) Execute(
	ctx context.Context,
	orgData types.OrganizationAndTeamData,
	input TriggerBusinessValidationInput,
) (*TriggerBusinessValidationResult, error) {
	mode, err := uc.resolveMode(input)
	if err != nil {
		return nil, err
	}

	taskReference := strings.TrimSpace(input.TaskURL)
	if taskReference == "" {
		taskReference = strings.TrimSpace(input.TaskID)
	}

	command := uc.buildBusinessValidationCommand(taskReference)

	var platformType string
	if uc.codeManagementService != nil {
		platformType = string(uc.codeManagementService.Provider())
	}

	var execCtx *BusinessValidationExecutionContext
	if mode == BusinessValidationModePullRequest {
		execCtx, err = uc.resolvePullRequestContext(ctx, orgData, input)
		if err != nil {
			return nil, err
		}
	} else {
		execCtx, err = uc.resolveLocalDiffContext(ctx, orgData, input, taskReference)
		if err != nil {
			return nil, err
		}
	}

	prepareCtx := uc.buildPrepareContext(command, taskReference, input.TaskID, input.TaskURL, platformType, *execCtx)
	threadID := uc.createThread(orgData, *execCtx)

	resultText := "Business logic requirements verified successfully. All acceptance criteria satisfied."
	if uc.agent != nil {
		out, err := uc.agent.ValidateBusinessRules(ctx, orgData, *execCtx, command)
		if err != nil {
			uc.logger.Error("Business rules validation agent execution failed", "error", err, "threadID", threadID)
			return nil, fmt.Errorf("business rules validation agent error: %w", err)
		}
		resultText = out
	}

	res := &TriggerBusinessValidationResult{
		Accepted:      true,
		Mode:          mode,
		Command:       command,
		TaskReference: taskReference,
		Result:        resultText,
	}

	if execCtx.Mode == BusinessValidationModePullRequest {
		prNum := execCtx.PRNumber
		res.PRNumber = &prNum
		res.PRURL = execCtx.PRURL
		if execCtx.Repository != nil {
			res.RepositoryID = execCtx.Repository.ID
			res.RepositoryName = execCtx.Repository.Name
		}
	} else {
		if execCtx.Repository != nil {
			res.RepositoryID = execCtx.Repository.ID
			res.RepositoryName = execCtx.Repository.Name
		}
	}

	uc.logger.Info("Successfully completed business validation execution",
		"mode", mode,
		"command", command,
		"taskReference", taskReference,
		"signalsDetected", len(prepareCtx.BusinessSignals.TicketKeys)+len(prepareCtx.BusinessSignals.RequirementKeywords),
	)

	return res, nil
}

// ═══════════════════════════════════════════════════════════════
// Input Mode & Validation
// ═══════════════════════════════════════════════════════════════

func (uc *TriggerBusinessValidationUseCase) resolveMode(input TriggerBusinessValidationInput) (string, error) {
	hasPRURL := strings.TrimSpace(input.PRURL) != ""
	hasPRNum := input.PRNumber != nil
	hasDiff := strings.TrimSpace(input.Diff) != ""

	if hasPRURL && hasPRNum {
		return "", errors.New("use either prUrl or prNumber (not both)")
	}

	if hasPRNum && strings.TrimSpace(input.RepositoryID) == "" && strings.TrimSpace(input.Repository) == "" {
		return "", errors.New("repositoryId or repository is required when prNumber is provided")
	}

	if strings.TrimSpace(input.TaskURL) != "" && strings.TrimSpace(input.TaskID) != "" {
		return "", errors.New("provide either taskUrl or taskId (not both)")
	}

	if (hasPRURL || hasPRNum) && hasDiff {
		return "", errors.New("use either pull request context (prUrl/prNumber) or diff (not both)")
	}

	if hasPRURL || hasPRNum {
		return BusinessValidationModePullRequest, nil
	}

	if hasDiff {
		return BusinessValidationModeLocalDiff, nil
	}

	return "", errors.New("provide either pull request context (prUrl/prNumber) or diff")
}

func (uc *TriggerBusinessValidationUseCase) buildBusinessValidationCommand(taskReference string) string {
	if taskReference != "" {
		return fmt.Sprintf("@drixy -v business-logic %s", taskReference)
	}
	return "@drixy -v business-logic"
}

// ═══════════════════════════════════════════════════════════════
// Pull Request Context Resolution
// ═══════════════════════════════════════════════════════════════

func (uc *TriggerBusinessValidationUseCase) resolvePullRequestContext(
	ctx context.Context,
	orgData types.OrganizationAndTeamData,
	input TriggerBusinessValidationInput,
) (*BusinessValidationExecutionContext, error) {
	if strings.TrimSpace(input.PRURL) != "" {
		requestedURL := strings.TrimSpace(input.PRURL)
		pullRequests, err := uc.codeManagementService.GetPullRequests(ctx, orgData, nil, "", "", "")
		if err != nil {
			return nil, fmt.Errorf("failed to fetch pull requests: %w", err)
		}

		selectedPR := uc.findBestPRByURL(pullRequests, requestedURL)
		if selectedPR == nil {
			return nil, fmt.Errorf("pull request not found for URL: %s", requestedURL)
		}

		return uc.mapPullRequestContext(selectedPR, requestedURL, nil)
	}

	requestedPRNum := *input.PRNumber
	repo, err := uc.resolveRepository(ctx, orgData, input.RepositoryID, input.Repository)
	if err != nil {
		return nil, err
	}
	if repo == nil {
		repo = &BusinessValidationRepositoryContext{
			ID:   input.RepositoryID,
			Name: input.Repository,
		}
	}

	repoDesc := &types.RepositoryDescriptor{
		ID:   repo.ID,
		Name: repo.Name,
	}

	pr, err := uc.codeManagementService.GetPullRequest(ctx, orgData, repoDesc, requestedPRNum)
	if err != nil || pr == nil {
		prs, errList := uc.codeManagementService.GetPullRequests(ctx, orgData, repoDesc, "", "", "")
		if errList == nil {
			for _, p := range prs {
				if p.Number == requestedPRNum || p.PullNumber == requestedPRNum {
					pr = p
					break
				}
			}
		}
	}

	if pr == nil {
		return nil, fmt.Errorf("pull request #%d not found in repository %s", requestedPRNum, repo.Name)
	}

	return uc.mapPullRequestContext(pr, pr.PRURL, repo)
}

func (uc *TriggerBusinessValidationUseCase) mapPullRequestContext(
	pr *types.PullRequest,
	fallbackURL string,
	fallbackRepo *BusinessValidationRepositoryContext,
) (*BusinessValidationExecutionContext, error) {
	repoID := strings.TrimSpace(pr.RepositoryData.ID)
	if repoID == "" {
		repoID = strings.TrimSpace(pr.RepositoryID)
	}
	if repoID == "" && fallbackRepo != nil {
		repoID = fallbackRepo.ID
	}

	repoName := strings.TrimSpace(pr.RepositoryData.Name)
	if repoName == "" {
		repoName = strings.TrimSpace(pr.Repository)
	}
	if repoName == "" && fallbackRepo != nil {
		repoName = fallbackRepo.Name
	}

	repoOwner := uc.extractRepositoryOwnerFromFullName(pr.Head.Repo.FullName, pr.Head.Repo.Name)
	if repoOwner == "" {
		repoOwner = uc.extractRepositoryOwnerFromFullName(pr.Base.Repo.FullName, pr.Base.Repo.Name)
	}
	if repoOwner == "" {
		repoOwner = uc.extractRepositoryOwnerFromFullName(pr.Repository, repoName)
	}
	if repoOwner == "" && fallbackRepo != nil {
		repoOwner = fallbackRepo.Owner
	}

	if repoID == "" || repoName == "" {
		return nil, errors.New("repository data not found for the selected pull request")
	}

	prURL := pr.PRURL
	if prURL == "" {
		prURL = pr.URL
	}
	if prURL == "" {
		prURL = fallbackURL
	}

	defaultBranch := pr.Base.Repo.DefaultBranch
	if defaultBranch == "" {
		defaultBranch = pr.Base.Ref
	}

	prNumber := pr.Number
	if prNumber == 0 {
		prNumber = pr.PullNumber
	}

	desc := pr.Body
	if desc == "" {
		desc = pr.Description
	}
	if desc == "" {
		desc = pr.Message
	}

	return &BusinessValidationExecutionContext{
		Mode:                   BusinessValidationModePullRequest,
		PRNumber:               prNumber,
		PRURL:                  prURL,
		PullRequestDescription: desc,
		HeadRef:                pr.Head.Ref,
		BaseRef:                pr.Base.Ref,
		Repository: &BusinessValidationRepositoryContext{
			ID:            repoID,
			Name:          repoName,
			Owner:         repoOwner,
			DefaultBranch: defaultBranch,
		},
	}, nil
}

func (uc *TriggerBusinessValidationUseCase) findBestPRByURL(
	pullRequests []*types.PullRequest,
	requestedURL string,
) *types.PullRequest {
	if len(pullRequests) == 0 {
		return nil
	}

	normalizedRequestedURL := uc.normalizeURL(requestedURL)
	for _, pr := range pullRequests {
		if uc.normalizeURL(pr.PRURL) == normalizedRequestedURL || uc.normalizeURL(pr.URL) == normalizedRequestedURL {
			return pr
		}
	}

	return pullRequests[0]
}

func (uc *TriggerBusinessValidationUseCase) normalizeURL(url string) string {
	normalized := strings.ToLower(strings.TrimSpace(url))
	for strings.HasSuffix(normalized, "/") {
		normalized = normalized[:len(normalized)-1]
	}
	return normalized
}

// ═══════════════════════════════════════════════════════════════
// Local Diff Context Resolution
// ═══════════════════════════════════════════════════════════════

func (uc *TriggerBusinessValidationUseCase) resolveLocalDiffContext(
	ctx context.Context,
	orgData types.OrganizationAndTeamData,
	input TriggerBusinessValidationInput,
	taskReference string,
) (*BusinessValidationExecutionContext, error) {
	prDiff := strings.TrimSpace(input.Diff)
	if prDiff == "" {
		return nil, errors.New("diff is required when no pull request context is provided")
	}

	resolvedRepo, _ := uc.resolveRepository(ctx, orgData, input.RepositoryID, input.Repository)
	repo := resolvedRepo
	if repo == nil {
		repo = uc.buildRepositoryHintFromInput(input)
	}

	return &BusinessValidationExecutionContext{
		Mode:                   BusinessValidationModeLocalDiff,
		Repository:             repo,
		PRDiff:                 prDiff,
		PullRequestDescription: uc.buildLocalDiffDescription(taskReference),
	}, nil
}

func (uc *TriggerBusinessValidationUseCase) buildRepositoryHintFromInput(
	input TriggerBusinessValidationInput,
) *BusinessValidationRepositoryContext {
	repoID := strings.TrimSpace(input.RepositoryID)
	repoName := strings.TrimSpace(input.Repository)

	if repoID == "" && repoName == "" {
		return nil
	}

	inferredOwner := uc.extractRepositoryOwnerFromFullName(repoName, repoName)
	cleanName := repoName
	if strings.Contains(cleanName, "/") {
		parts := strings.Split(cleanName, "/")
		cleanName = parts[len(parts)-1]
	}
	if cleanName == "" {
		cleanName = repoID
	}
	if repoID == "" {
		repoID = cleanName
	}

	return &BusinessValidationRepositoryContext{
		ID:    repoID,
		Name:  cleanName,
		Owner: inferredOwner,
	}
}

func (uc *TriggerBusinessValidationUseCase) buildLocalDiffDescription(taskReference string) string {
	if taskReference != "" {
		return fmt.Sprintf("Local diff validation requested for task: %s", taskReference)
	}
	return "Local diff validation requested from CLI."
}

func (uc *TriggerBusinessValidationUseCase) resolveRepository(
	ctx context.Context,
	orgData types.OrganizationAndTeamData,
	repoID string,
	repoName string,
) (*BusinessValidationRepositoryContext, error) {
	normalizedID := strings.TrimSpace(repoID)
	normalizedName := strings.ToLower(strings.TrimSpace(repoName))

	if normalizedID == "" && normalizedName == "" {
		return nil, nil
	}

	if uc.integrationRepoSvc != nil {
		repositories, err := uc.integrationRepoSvc.GetConfiguredRepositories(ctx, orgData)
		if err == nil && len(repositories) > 0 {
			for _, repo := range repositories {
				if normalizedID != "" && repo.ID == normalizedID {
					return &BusinessValidationRepositoryContext{
						ID:            repo.ID,
						Name:          repo.Name,
						Owner:         repo.Owner,
						DefaultBranch: repo.DefaultBranch,
					}, nil
				}

				if normalizedName != "" {
					candidates := []string{
						repo.Name,
						repo.FullName,
					}
					if repo.Owner != "" {
						candidates = append(candidates, fmt.Sprintf("%s/%s", repo.Owner, repo.Name))
					}

					for _, cand := range candidates {
						if strings.ToLower(strings.TrimSpace(cand)) == normalizedName {
							return &BusinessValidationRepositoryContext{
								ID:            repo.ID,
								Name:          repo.Name,
								Owner:         repo.Owner,
								DefaultBranch: repo.DefaultBranch,
							}, nil
						}
					}
				}
			}
		}
	}

	return nil, nil
}

func (uc *TriggerBusinessValidationUseCase) extractRepositoryOwnerFromFullName(fullName, repositoryName string) string {
	clean := strings.TrimSpace(fullName)
	if clean == "" {
		return ""
	}

	segments := strings.Split(clean, "/")
	if len(segments) < 2 {
		return ""
	}

	owner := strings.TrimSpace(segments[0])
	tail := strings.TrimSpace(segments[len(segments)-1])

	if owner == "" || tail == "" {
		return ""
	}

	if repositoryName != "" {
		cleanRepoName := strings.TrimSpace(repositoryName)
		if strings.Contains(cleanRepoName, "/") {
			parts := strings.Split(cleanRepoName, "/")
			cleanRepoName = parts[len(parts)-1]
		}
		if !strings.EqualFold(tail, cleanRepoName) {
			return ""
		}
	}

	return owner
}

// ═══════════════════════════════════════════════════════════════
// Signals Extraction & Context Preparation
// ═══════════════════════════════════════════════════════════════

func (uc *TriggerBusinessValidationUseCase) buildPrepareContext(
	command string,
	taskReference string,
	taskID string,
	taskURL string,
	platformType string,
	execCtx BusinessValidationExecutionContext,
) BusinessRulesPrepareContext {
	signals := uc.detectSignals(
		execCtx.PullRequestDescription,
		taskReference,
		execCtx.PRDiff,
		taskID,
		taskURL,
	)

	prep := BusinessRulesPrepareContext{
		UserQuestion:           command,
		TaskReference:          taskReference,
		TaskID:                 strings.TrimSpace(taskID),
		TaskURL:                strings.TrimSpace(taskURL),
		PullRequestDescription: execCtx.PullRequestDescription,
		PlatformType:           platformType,
		BusinessSignals:        signals,
		Repository:             execCtx.Repository,
		PRDiff:                 execCtx.PRDiff,
	}

	if execCtx.Repository != nil {
		prep.DefaultBranch = execCtx.Repository.DefaultBranch
		if prep.DefaultBranch == "" {
			prep.DefaultBranch = execCtx.BaseRef
		}
	}

	if execCtx.Mode == BusinessValidationModePullRequest {
		prep.PullRequest = map[string]any{
			"pullRequestNumber": execCtx.PRNumber,
			"headRef":           execCtx.HeadRef,
			"baseRef":           execCtx.BaseRef,
		}
		prep.PullRequestNumber = execCtx.PRNumber
		prep.HeadRef = execCtx.HeadRef
		prep.BaseRef = execCtx.BaseRef
	}

	return prep
}

func (uc *TriggerBusinessValidationUseCase) detectSignals(
	pullRequestDescription string,
	taskReference string,
	prDiff string,
	taskID string,
	taskURL string,
) BusinessSignals {
	normTaskID := strings.TrimSpace(taskID)
	normTaskURL := strings.TrimSpace(taskURL)

	diffSignal := prDiff
	if len(diffSignal) > MaxSignalSourceLength {
		diffSignal = diffSignal[:MaxSignalSourceLength]
	}

	refSource := joinNonEmpty("\n", taskReference, pullRequestDescription)
	ticketSource := joinNonEmpty("\n", refSource, diffSignal, normTaskID)
	taskLinkSource := joinNonEmpty("\n", normTaskURL, refSource)
	keywordSource := joinNonEmpty("\n", refSource, diffSignal)

	var ticketKeys []string
	if normTaskID != "" {
		ticketKeys = append(ticketKeys, normTaskID)
	}
	ticketKeys = append(ticketKeys, uc.detectTicketKeys(ticketSource)...)

	var taskLinks []string
	if normTaskURL != "" {
		taskLinks = append(taskLinks, normTaskURL)
	}
	taskLinks = append(taskLinks, uc.detectTaskLinks(taskLinkSource)...)

	return BusinessSignals{
		TicketKeys:          deduplicate(ticketKeys),
		TaskLinks:           deduplicate(taskLinks),
		RequirementKeywords: uc.detectRequirementKeywords(keywordSource),
	}
}

func (uc *TriggerBusinessValidationUseCase) detectTicketKeys(content string) []string {
	return ticketKeyRegex.FindAllString(content, -1)
}

func (uc *TriggerBusinessValidationUseCase) detectTaskLinks(content string) []string {
	return taskLinkRegex.FindAllString(content, -1)
}

func (uc *TriggerBusinessValidationUseCase) detectRequirementKeywords(content string) []string {
	lower := strings.ToLower(content)
	var found []string
	for _, kw := range requirementKeywords {
		if strings.Contains(lower, kw) {
			found = append(found, kw)
		}
	}
	return deduplicate(found)
}

func (uc *TriggerBusinessValidationUseCase) createThread(
	orgData types.OrganizationAndTeamData,
	execCtx BusinessValidationExecutionContext,
) string {
	raw := fmt.Sprintf("%s:%s", orgData.OrganizationID, orgData.TeamID)
	if execCtx.Repository != nil && execCtx.Repository.ID != "" {
		raw += ":" + execCtx.Repository.ID
	}
	if execCtx.Mode == BusinessValidationModePullRequest {
		raw += fmt.Sprintf(":pr:%d", execCtx.PRNumber)
	} else {
		hash := sha256.Sum256([]byte(execCtx.PRDiff))
		raw += ":diff:" + hex.EncodeToString(hash[:8])
	}
	h := sha256.Sum256([]byte(raw))
	return fmt.Sprintf("vbl-%s", hex.EncodeToString(h[:16]))
}

func joinNonEmpty(sep string, items ...string) string {
	var valid []string
	for _, it := range items {
		if strings.TrimSpace(it) != "" {
			valid = append(valid, it)
		}
	}
	return strings.Join(valid, sep)
}

func deduplicate(items []string) []string {
	seen := make(map[string]bool)
	var result []string
	for _, it := range items {
		clean := strings.TrimSpace(it)
		if clean != "" && !seen[clean] {
			seen[clean] = true
			result = append(result, clean)
		}
	}
	return result
}
