// ═══════════════════════════════════════════════════════════════
// ScanDrix AI - Enterprise Rule System
// File: find_suggestions_by_rule.go
// ═══════════════════════════════════════════════════════════════

package usecases

import (
	"context"
	"fmt"

	"github.com/scandrix/backend/internal/rules/drixy/domain/contracts"
)

// RuleSuggestion describes an automated review comment generated by a rule.
type RuleSuggestion struct {
	ID             string `json:"id"`
	RuleID         string `json:"ruleId"`
	PullRequestID  string `json:"pullRequestId"`
	RepositoryID   string `json:"repositoryId"`
	FilePath       string `json:"filePath"`
	LineNumber     int    `json:"lineNumber"`
	Comment        string `json:"comment"`
	Severity       string `json:"severity"`
	AcceptedByUser bool   `json:"acceptedByUser"`
	CreatedAt      string `json:"createdAt"`
}

// IPullRequestSuggestionsProvider abstracts retrieval of past PR comments spawned by rules.
type IPullRequestSuggestionsProvider interface {
	FindSuggestionsByRuleID(ctx context.Context, ruleID, organizationID string) ([]RuleSuggestion, error)
}

// FindSuggestionsByRuleUseCase retrieves PR review suggestions historically produced by a rule.
type FindSuggestionsByRuleUseCase struct {
	rulesService        contracts.IDrixyRulesService
	suggestionsProvider IPullRequestSuggestionsProvider
}

// NewFindSuggestionsByRuleUseCase constructs the use case.
func NewFindSuggestionsByRuleUseCase(
	rulesService contracts.IDrixyRulesService,
	suggestionsProvider IPullRequestSuggestionsProvider,
) *FindSuggestionsByRuleUseCase {
	return &FindSuggestionsByRuleUseCase{
		rulesService:        rulesService,
		suggestionsProvider: suggestionsProvider,
	}
}

// Execute queries suggestions originating from the specified rule.
func (uc *FindSuggestionsByRuleUseCase) Execute(
	ctx context.Context,
	organizationID, ruleID string,
) ([]RuleSuggestion, error) {
	if organizationID == "" {
		return nil, fmt.Errorf("organization ID is required")
	}
	if ruleID == "" {
		return nil, fmt.Errorf("rule ID is required")
	}

	entity, err := uc.rulesService.FindByOrganizationID(ctx, organizationID)
	if err != nil {
		return nil, fmt.Errorf("failed to load organization rules: %w", err)
	}
	if entity == nil {
		return nil, fmt.Errorf("no rules found for organization")
	}

	found := false
	for _, r := range entity.Rules() {
		if r.UUID == ruleID {
			found = true
			break
		}
	}
	if !found {
		return nil, fmt.Errorf("rule not found or does not belong to organization")
	}

	if uc.suggestionsProvider == nil {
		return []RuleSuggestion{}, nil
	}

	suggestions, err := uc.suggestionsProvider.FindSuggestionsByRuleID(ctx, ruleID, organizationID)
	if err != nil {
		return nil, fmt.Errorf("failed to load suggestions: %w", err)
	}

	if suggestions == nil {
		return []RuleSuggestion{}, nil
	}

	return suggestions, nil
}
